[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["go", "nodejs", "gcc", "pkg-config", "sqlite"]

[phases.install]
cmds = [
    "go mod download",
    "npm install"
]

[phases.build]
cmds = [
    # Build frontend
    "npx vite build",
    
    # Debug - show what files are created by Vite build
    "echo 'Listing public directory:' && ls -la public",
    "echo 'Listing public/build directory:' && ls -la public/build",
    
    # Create needed directories for static files
    "mkdir -p /app/static",
    
    # Make sure the manifest files and assets are copied correctly
    "cp -r public/* /app/static/",
    
    # Verify files were copied correctly
    "echo 'Verifying static directory:' && ls -la /app/static",
    "echo 'Verifying static/build directory:' && ls -la /app/static/build",
    
    # Create the root files directory that matches our /files/ URL path
    "mkdir -p /app/files",
    "cp -r public/build/assets /app/files/",
    "echo 'Verifying files directory:' && ls -la /app/files",
    "echo 'Verifying files/assets directory:' && ls -la /app/files/assets",
    
    # Build Go binary
    "CGO_ENABLED=1 go build -o pagode ./cmd/web"
]

[start]
cmd = "./pagode --port $PORT"

[variables]
PORT = "8000"
CGO_ENABLED = "1"
NODE_ENV = "production"
PAGODA_APP_ENVIRONMENT = "prod"