[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["go", "nodejs", "gcc", "pkg-config", "sqlite"]

[phases.install]
cmds = [
    "go mod download",
    "npm install"
]

[phases.build]
cmds = [
    # Build frontend
    "npx vite build",
    
    # Create target directory (absolute path to ensure location)
    "mkdir -p /app/static/public/build",
    
    # Copy with preserved permissions (verbose for debugging)
    "cp -rv public/build /app/static/public/",
    
    # Build Go binary
    "CGO_ENABLED=1 go build -o pagode ./cmd/web",
    
    # Verification step (will appear in build logs)
    "echo 'Verifying files were copied:' && ls -la /app/static/public/build"
]

[start]
cmd = "./pagode --port $PORT"

[variables]
PORT = "8000"
CGO_ENABLED = "1"
NODE_ENV = "production"