// Code generated by ent, DO NOT EDIT.

package chatban

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/occult/pagode/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldLTE(FieldID, id))
}

// IPHash applies equality check predicate on the "ip_hash" field. It's identical to IPHashEQ.
func IPHash(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldEQ(FieldIPHash, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldEQ(FieldReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldEQ(FieldCreatedAt, v))
}

// IPHashEQ applies the EQ predicate on the "ip_hash" field.
func IPHashEQ(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldEQ(FieldIPHash, v))
}

// IPHashNEQ applies the NEQ predicate on the "ip_hash" field.
func IPHashNEQ(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldNEQ(FieldIPHash, v))
}

// IPHashIn applies the In predicate on the "ip_hash" field.
func IPHashIn(vs ...string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldIn(FieldIPHash, vs...))
}

// IPHashNotIn applies the NotIn predicate on the "ip_hash" field.
func IPHashNotIn(vs ...string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldNotIn(FieldIPHash, vs...))
}

// IPHashGT applies the GT predicate on the "ip_hash" field.
func IPHashGT(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldGT(FieldIPHash, v))
}

// IPHashGTE applies the GTE predicate on the "ip_hash" field.
func IPHashGTE(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldGTE(FieldIPHash, v))
}

// IPHashLT applies the LT predicate on the "ip_hash" field.
func IPHashLT(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldLT(FieldIPHash, v))
}

// IPHashLTE applies the LTE predicate on the "ip_hash" field.
func IPHashLTE(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldLTE(FieldIPHash, v))
}

// IPHashContains applies the Contains predicate on the "ip_hash" field.
func IPHashContains(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldContains(FieldIPHash, v))
}

// IPHashHasPrefix applies the HasPrefix predicate on the "ip_hash" field.
func IPHashHasPrefix(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldHasPrefix(FieldIPHash, v))
}

// IPHashHasSuffix applies the HasSuffix predicate on the "ip_hash" field.
func IPHashHasSuffix(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldHasSuffix(FieldIPHash, v))
}

// IPHashIsNil applies the IsNil predicate on the "ip_hash" field.
func IPHashIsNil() predicate.ChatBan {
	return predicate.ChatBan(sql.FieldIsNull(FieldIPHash))
}

// IPHashNotNil applies the NotNil predicate on the "ip_hash" field.
func IPHashNotNil() predicate.ChatBan {
	return predicate.ChatBan(sql.FieldNotNull(FieldIPHash))
}

// IPHashEqualFold applies the EqualFold predicate on the "ip_hash" field.
func IPHashEqualFold(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldEqualFold(FieldIPHash, v))
}

// IPHashContainsFold applies the ContainsFold predicate on the "ip_hash" field.
func IPHashContainsFold(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldContainsFold(FieldIPHash, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.ChatBan {
	return predicate.ChatBan(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.ChatBan {
	return predicate.ChatBan(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldContainsFold(FieldReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChatBan {
	return predicate.ChatBan(sql.FieldLTE(FieldCreatedAt, v))
}

// HasRoom applies the HasEdge predicate on the "room" edge.
func HasRoom() predicate.ChatBan {
	return predicate.ChatBan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoomTable, RoomColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoomWith applies the HasEdge predicate on the "room" edge with a given conditions (other predicates).
func HasRoomWith(preds ...predicate.ChatRoom) predicate.ChatBan {
	return predicate.ChatBan(func(s *sql.Selector) {
		step := newRoomStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ChatBan {
	return predicate.ChatBan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ChatBan {
	return predicate.ChatBan(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBannedByUser applies the HasEdge predicate on the "banned_by_user" edge.
func HasBannedByUser() predicate.ChatBan {
	return predicate.ChatBan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BannedByUserTable, BannedByUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBannedByUserWith applies the HasEdge predicate on the "banned_by_user" edge with a given conditions (other predicates).
func HasBannedByUserWith(preds ...predicate.User) predicate.ChatBan {
	return predicate.ChatBan(func(s *sql.Selector) {
		step := newBannedByUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChatBan) predicate.ChatBan {
	return predicate.ChatBan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChatBan) predicate.ChatBan {
	return predicate.ChatBan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChatBan) predicate.ChatBan {
	return predicate.ChatBan(sql.NotPredicates(p))
}
