// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/occult/pagode/ent/chatmessage"
	"github.com/occult/pagode/ent/chatroom"
	"github.com/occult/pagode/ent/user"
)

// ChatMessageCreate is the builder for creating a ChatMessage entity.
type ChatMessageCreate struct {
	config
	mutation *ChatMessageMutation
	hooks    []Hook
}

// SetBody sets the "body" field.
func (_c *ChatMessageCreate) SetBody(v string) *ChatMessageCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetSenderName sets the "sender_name" field.
func (_c *ChatMessageCreate) SetSenderName(v string) *ChatMessageCreate {
	_c.mutation.SetSenderName(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatMessageCreate) SetCreatedAt(v time.Time) *ChatMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableCreatedAt(v *time.Time) *ChatMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRoomID sets the "room" edge to the ChatRoom entity by ID.
func (_c *ChatMessageCreate) SetRoomID(id int) *ChatMessageCreate {
	_c.mutation.SetRoomID(id)
	return _c
}

// SetRoom sets the "room" edge to the ChatRoom entity.
func (_c *ChatMessageCreate) SetRoom(v *ChatRoom) *ChatMessageCreate {
	return _c.SetRoomID(v.ID)
}

// SetSenderID sets the "sender" edge to the User entity by ID.
func (_c *ChatMessageCreate) SetSenderID(id int) *ChatMessageCreate {
	_c.mutation.SetSenderID(id)
	return _c
}

// SetNillableSenderID sets the "sender" edge to the User entity by ID if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableSenderID(id *int) *ChatMessageCreate {
	if id != nil {
		_c = _c.SetSenderID(*id)
	}
	return _c
}

// SetSender sets the "sender" edge to the User entity.
func (_c *ChatMessageCreate) SetSender(v *User) *ChatMessageCreate {
	return _c.SetSenderID(v.ID)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_c *ChatMessageCreate) Mutation() *ChatMessageMutation {
	return _c.mutation
}

// Save creates the ChatMessage in the database.
func (_c *ChatMessageCreate) Save(ctx context.Context) (*ChatMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatMessageCreate) SaveX(ctx context.Context) *ChatMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatMessageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatMessageCreate) check() error {
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "ChatMessage.body"`)}
	}
	if v, ok := _c.mutation.Body(); ok {
		if err := chatmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.body": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SenderName(); !ok {
		return &ValidationError{Name: "sender_name", err: errors.New(`ent: missing required field "ChatMessage.sender_name"`)}
	}
	if v, ok := _c.mutation.SenderName(); ok {
		if err := chatmessage.SenderNameValidator(v); err != nil {
			return &ValidationError{Name: "sender_name", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.sender_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatMessage.created_at"`)}
	}
	if len(_c.mutation.RoomIDs()) == 0 {
		return &ValidationError{Name: "room", err: errors.New(`ent: missing required edge "ChatMessage.room"`)}
	}
	return nil
}

func (_c *ChatMessageCreate) sqlSave(ctx context.Context) (*ChatMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatMessageCreate) createSpec() (*ChatMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatmessage.Table, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(chatmessage.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.SenderName(); ok {
		_spec.SetField(chatmessage.FieldSenderName, field.TypeString, value)
		_node.SenderName = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.RoomTable,
			Columns: []string{chatmessage.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.chat_room_messages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.SenderTable,
			Columns: []string{chatmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_chat_messages = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatMessageCreateBulk is the builder for creating many ChatMessage entities in bulk.
type ChatMessageCreateBulk struct {
	config
	err      error
	builders []*ChatMessageCreate
}

// Save creates the ChatMessage entities in the database.
func (_c *ChatMessageCreateBulk) Save(ctx context.Context) ([]*ChatMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatMessageCreateBulk) SaveX(ctx context.Context) []*ChatMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
