// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/occult/pagode/ent/chatban"
	"github.com/occult/pagode/ent/chatmessage"
	"github.com/occult/pagode/ent/chatroom"
	"github.com/occult/pagode/ent/predicate"
	"github.com/occult/pagode/ent/user"
)

// ChatRoomUpdate is the builder for updating ChatRoom entities.
type ChatRoomUpdate struct {
	config
	hooks    []Hook
	mutation *ChatRoomMutation
}

// Where appends a list predicates to the ChatRoomUpdate builder.
func (_u *ChatRoomUpdate) Where(ps ...predicate.ChatRoom) *ChatRoomUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ChatRoomUpdate) SetName(v string) *ChatRoomUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChatRoomUpdate) SetNillableName(v *string) *ChatRoomUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *ChatRoomUpdate) SetIsPublic(v bool) *ChatRoomUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *ChatRoomUpdate) SetNillableIsPublic(v *bool) *ChatRoomUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *ChatRoomUpdate) SetPasswordHash(v string) *ChatRoomUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *ChatRoomUpdate) SetNillablePasswordHash(v *string) *ChatRoomUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *ChatRoomUpdate) ClearPasswordHash() *ChatRoomUpdate {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ChatRoomUpdate) SetOwnerID(id int) *ChatRoomUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *ChatRoomUpdate) SetNillableOwnerID(id *int) *ChatRoomUpdate {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ChatRoomUpdate) SetOwner(v *User) *ChatRoomUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the ChatMessage entity by IDs.
func (_u *ChatRoomUpdate) AddMessageIDs(ids ...int) *ChatRoomUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the ChatMessage entity.
func (_u *ChatRoomUpdate) AddMessages(v ...*ChatMessage) *ChatRoomUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// AddBanIDs adds the "bans" edge to the ChatBan entity by IDs.
func (_u *ChatRoomUpdate) AddBanIDs(ids ...int) *ChatRoomUpdate {
	_u.mutation.AddBanIDs(ids...)
	return _u
}

// AddBans adds the "bans" edges to the ChatBan entity.
func (_u *ChatRoomUpdate) AddBans(v ...*ChatBan) *ChatRoomUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBanIDs(ids...)
}

// Mutation returns the ChatRoomMutation object of the builder.
func (_u *ChatRoomUpdate) Mutation() *ChatRoomMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ChatRoomUpdate) ClearOwner() *ChatRoomUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearMessages clears all "messages" edges to the ChatMessage entity.
func (_u *ChatRoomUpdate) ClearMessages() *ChatRoomUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to ChatMessage entities by IDs.
func (_u *ChatRoomUpdate) RemoveMessageIDs(ids ...int) *ChatRoomUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to ChatMessage entities.
func (_u *ChatRoomUpdate) RemoveMessages(v ...*ChatMessage) *ChatRoomUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// ClearBans clears all "bans" edges to the ChatBan entity.
func (_u *ChatRoomUpdate) ClearBans() *ChatRoomUpdate {
	_u.mutation.ClearBans()
	return _u
}

// RemoveBanIDs removes the "bans" edge to ChatBan entities by IDs.
func (_u *ChatRoomUpdate) RemoveBanIDs(ids ...int) *ChatRoomUpdate {
	_u.mutation.RemoveBanIDs(ids...)
	return _u
}

// RemoveBans removes "bans" edges to ChatBan entities.
func (_u *ChatRoomUpdate) RemoveBans(v ...*ChatBan) *ChatRoomUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBanIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatRoomUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatRoomUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatRoomUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatRoomUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatRoomUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := chatroom.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChatRoom.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ChatRoomUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatroom.Table, chatroom.Columns, sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(chatroom.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(chatroom.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(chatroom.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(chatroom.FieldPasswordHash, field.TypeString)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroom.OwnerTable,
			Columns: []string{chatroom.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroom.OwnerTable,
			Columns: []string{chatroom.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.MessagesTable,
			Columns: []string{chatroom.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.MessagesTable,
			Columns: []string{chatroom.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.MessagesTable,
			Columns: []string{chatroom.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.BansTable,
			Columns: []string{chatroom.BansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatban.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBansIDs(); len(nodes) > 0 && !_u.mutation.BansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.BansTable,
			Columns: []string{chatroom.BansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatban.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.BansTable,
			Columns: []string{chatroom.BansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatban.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatroom.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatRoomUpdateOne is the builder for updating a single ChatRoom entity.
type ChatRoomUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatRoomMutation
}

// SetName sets the "name" field.
func (_u *ChatRoomUpdateOne) SetName(v string) *ChatRoomUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChatRoomUpdateOne) SetNillableName(v *string) *ChatRoomUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *ChatRoomUpdateOne) SetIsPublic(v bool) *ChatRoomUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *ChatRoomUpdateOne) SetNillableIsPublic(v *bool) *ChatRoomUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *ChatRoomUpdateOne) SetPasswordHash(v string) *ChatRoomUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *ChatRoomUpdateOne) SetNillablePasswordHash(v *string) *ChatRoomUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// ClearPasswordHash clears the value of the "password_hash" field.
func (_u *ChatRoomUpdateOne) ClearPasswordHash() *ChatRoomUpdateOne {
	_u.mutation.ClearPasswordHash()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ChatRoomUpdateOne) SetOwnerID(id int) *ChatRoomUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (_u *ChatRoomUpdateOne) SetNillableOwnerID(id *int) *ChatRoomUpdateOne {
	if id != nil {
		_u = _u.SetOwnerID(*id)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ChatRoomUpdateOne) SetOwner(v *User) *ChatRoomUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the ChatMessage entity by IDs.
func (_u *ChatRoomUpdateOne) AddMessageIDs(ids ...int) *ChatRoomUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the ChatMessage entity.
func (_u *ChatRoomUpdateOne) AddMessages(v ...*ChatMessage) *ChatRoomUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// AddBanIDs adds the "bans" edge to the ChatBan entity by IDs.
func (_u *ChatRoomUpdateOne) AddBanIDs(ids ...int) *ChatRoomUpdateOne {
	_u.mutation.AddBanIDs(ids...)
	return _u
}

// AddBans adds the "bans" edges to the ChatBan entity.
func (_u *ChatRoomUpdateOne) AddBans(v ...*ChatBan) *ChatRoomUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBanIDs(ids...)
}

// Mutation returns the ChatRoomMutation object of the builder.
func (_u *ChatRoomUpdateOne) Mutation() *ChatRoomMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ChatRoomUpdateOne) ClearOwner() *ChatRoomUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearMessages clears all "messages" edges to the ChatMessage entity.
func (_u *ChatRoomUpdateOne) ClearMessages() *ChatRoomUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to ChatMessage entities by IDs.
func (_u *ChatRoomUpdateOne) RemoveMessageIDs(ids ...int) *ChatRoomUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to ChatMessage entities.
func (_u *ChatRoomUpdateOne) RemoveMessages(v ...*ChatMessage) *ChatRoomUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// ClearBans clears all "bans" edges to the ChatBan entity.
func (_u *ChatRoomUpdateOne) ClearBans() *ChatRoomUpdateOne {
	_u.mutation.ClearBans()
	return _u
}

// RemoveBanIDs removes the "bans" edge to ChatBan entities by IDs.
func (_u *ChatRoomUpdateOne) RemoveBanIDs(ids ...int) *ChatRoomUpdateOne {
	_u.mutation.RemoveBanIDs(ids...)
	return _u
}

// RemoveBans removes "bans" edges to ChatBan entities.
func (_u *ChatRoomUpdateOne) RemoveBans(v ...*ChatBan) *ChatRoomUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBanIDs(ids...)
}

// Where appends a list predicates to the ChatRoomUpdate builder.
func (_u *ChatRoomUpdateOne) Where(ps ...predicate.ChatRoom) *ChatRoomUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatRoomUpdateOne) Select(field string, fields ...string) *ChatRoomUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatRoom entity.
func (_u *ChatRoomUpdateOne) Save(ctx context.Context) (*ChatRoom, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatRoomUpdateOne) SaveX(ctx context.Context) *ChatRoom {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatRoomUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatRoomUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatRoomUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := chatroom.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChatRoom.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ChatRoomUpdateOne) sqlSave(ctx context.Context) (_node *ChatRoom, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatroom.Table, chatroom.Columns, sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatRoom.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatroom.FieldID)
		for _, f := range fields {
			if !chatroom.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatroom.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(chatroom.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(chatroom.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(chatroom.FieldPasswordHash, field.TypeString, value)
	}
	if _u.mutation.PasswordHashCleared() {
		_spec.ClearField(chatroom.FieldPasswordHash, field.TypeString)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroom.OwnerTable,
			Columns: []string{chatroom.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatroom.OwnerTable,
			Columns: []string{chatroom.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.MessagesTable,
			Columns: []string{chatroom.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.MessagesTable,
			Columns: []string{chatroom.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.MessagesTable,
			Columns: []string{chatroom.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.BansTable,
			Columns: []string{chatroom.BansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatban.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBansIDs(); len(nodes) > 0 && !_u.mutation.BansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.BansTable,
			Columns: []string{chatroom.BansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatban.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatroom.BansTable,
			Columns: []string{chatroom.BansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatban.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatRoom{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatroom.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
