// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/occult/pagode/ent/chatban"
	"github.com/occult/pagode/ent/chatroom"
	"github.com/occult/pagode/ent/user"
)

// ChatBan is the model entity for the ChatBan schema.
type ChatBan struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IPHash holds the value of the "ip_hash" field.
	IPHash string `json:"ip_hash,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChatBanQuery when eager-loading is set.
	Edges                 ChatBanEdges `json:"edges"`
	chat_room_bans        *int
	user_chat_bans        *int
	user_chat_bans_issued *int
	selectValues          sql.SelectValues
}

// ChatBanEdges holds the relations/edges for other nodes in the graph.
type ChatBanEdges struct {
	// Room holds the value of the room edge.
	Room *ChatRoom `json:"room,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// BannedByUser holds the value of the banned_by_user edge.
	BannedByUser *User `json:"banned_by_user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// RoomOrErr returns the Room value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatBanEdges) RoomOrErr() (*ChatRoom, error) {
	if e.Room != nil {
		return e.Room, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: chatroom.Label}
	}
	return nil, &NotLoadedError{edge: "room"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatBanEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// BannedByUserOrErr returns the BannedByUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatBanEdges) BannedByUserOrErr() (*User, error) {
	if e.BannedByUser != nil {
		return e.BannedByUser, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "banned_by_user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChatBan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatban.FieldID:
			values[i] = new(sql.NullInt64)
		case chatban.FieldIPHash, chatban.FieldReason:
			values[i] = new(sql.NullString)
		case chatban.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case chatban.ForeignKeys[0]: // chat_room_bans
			values[i] = new(sql.NullInt64)
		case chatban.ForeignKeys[1]: // user_chat_bans
			values[i] = new(sql.NullInt64)
		case chatban.ForeignKeys[2]: // user_chat_bans_issued
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChatBan fields.
func (_m *ChatBan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatban.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case chatban.FieldIPHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip_hash", values[i])
			} else if value.Valid {
				_m.IPHash = value.String
			}
		case chatban.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case chatban.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case chatban.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field chat_room_bans", value)
			} else if value.Valid {
				_m.chat_room_bans = new(int)
				*_m.chat_room_bans = int(value.Int64)
			}
		case chatban.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_chat_bans", value)
			} else if value.Valid {
				_m.user_chat_bans = new(int)
				*_m.user_chat_bans = int(value.Int64)
			}
		case chatban.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_chat_bans_issued", value)
			} else if value.Valid {
				_m.user_chat_bans_issued = new(int)
				*_m.user_chat_bans_issued = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChatBan.
// This includes values selected through modifiers, order, etc.
func (_m *ChatBan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoom queries the "room" edge of the ChatBan entity.
func (_m *ChatBan) QueryRoom() *ChatRoomQuery {
	return NewChatBanClient(_m.config).QueryRoom(_m)
}

// QueryUser queries the "user" edge of the ChatBan entity.
func (_m *ChatBan) QueryUser() *UserQuery {
	return NewChatBanClient(_m.config).QueryUser(_m)
}

// QueryBannedByUser queries the "banned_by_user" edge of the ChatBan entity.
func (_m *ChatBan) QueryBannedByUser() *UserQuery {
	return NewChatBanClient(_m.config).QueryBannedByUser(_m)
}

// Update returns a builder for updating this ChatBan.
// Note that you need to call ChatBan.Unwrap() before calling this method if this ChatBan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChatBan) Update() *ChatBanUpdateOne {
	return NewChatBanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChatBan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChatBan) Unwrap() *ChatBan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChatBan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChatBan) String() string {
	var builder strings.Builder
	builder.WriteString("ChatBan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ip_hash=")
	builder.WriteString(_m.IPHash)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChatBans is a parsable slice of ChatBan.
type ChatBans []*ChatBan
