// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/occult/pagode/ent/chatmessage"
	"github.com/occult/pagode/ent/chatroom"
	"github.com/occult/pagode/ent/predicate"
	"github.com/occult/pagode/ent/user"
)

// ChatMessageUpdate is the builder for updating ChatMessage entities.
type ChatMessageUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMessageMutation
}

// Where appends a list predicates to the ChatMessageUpdate builder.
func (_u *ChatMessageUpdate) Where(ps ...predicate.ChatMessage) *ChatMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBody sets the "body" field.
func (_u *ChatMessageUpdate) SetBody(v string) *ChatMessageUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableBody(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetSenderName sets the "sender_name" field.
func (_u *ChatMessageUpdate) SetSenderName(v string) *ChatMessageUpdate {
	_u.mutation.SetSenderName(v)
	return _u
}

// SetNillableSenderName sets the "sender_name" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableSenderName(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetSenderName(*v)
	}
	return _u
}

// SetRoomID sets the "room" edge to the ChatRoom entity by ID.
func (_u *ChatMessageUpdate) SetRoomID(id int) *ChatMessageUpdate {
	_u.mutation.SetRoomID(id)
	return _u
}

// SetRoom sets the "room" edge to the ChatRoom entity.
func (_u *ChatMessageUpdate) SetRoom(v *ChatRoom) *ChatMessageUpdate {
	return _u.SetRoomID(v.ID)
}

// SetSenderID sets the "sender" edge to the User entity by ID.
func (_u *ChatMessageUpdate) SetSenderID(id int) *ChatMessageUpdate {
	_u.mutation.SetSenderID(id)
	return _u
}

// SetNillableSenderID sets the "sender" edge to the User entity by ID if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableSenderID(id *int) *ChatMessageUpdate {
	if id != nil {
		_u = _u.SetSenderID(*id)
	}
	return _u
}

// SetSender sets the "sender" edge to the User entity.
func (_u *ChatMessageUpdate) SetSender(v *User) *ChatMessageUpdate {
	return _u.SetSenderID(v.ID)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_u *ChatMessageUpdate) Mutation() *ChatMessageMutation {
	return _u.mutation
}

// ClearRoom clears the "room" edge to the ChatRoom entity.
func (_u *ChatMessageUpdate) ClearRoom() *ChatMessageUpdate {
	_u.mutation.ClearRoom()
	return _u
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *ChatMessageUpdate) ClearSender() *ChatMessageUpdate {
	_u.mutation.ClearSender()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageUpdate) check() error {
	if v, ok := _u.mutation.Body(); ok {
		if err := chatmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SenderName(); ok {
		if err := chatmessage.SenderNameValidator(v); err != nil {
			return &ValidationError{Name: "sender_name", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.sender_name": %w`, err)}
		}
	}
	if _u.mutation.RoomCleared() && len(_u.mutation.RoomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessage.room"`)
	}
	return nil
}

func (_u *ChatMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessage.Table, chatmessage.Columns, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(chatmessage.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderName(); ok {
		_spec.SetField(chatmessage.FieldSenderName, field.TypeString, value)
	}
	if _u.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.RoomTable,
			Columns: []string{chatmessage.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.RoomTable,
			Columns: []string{chatmessage.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.SenderTable,
			Columns: []string{chatmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.SenderTable,
			Columns: []string{chatmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatMessageUpdateOne is the builder for updating a single ChatMessage entity.
type ChatMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMessageMutation
}

// SetBody sets the "body" field.
func (_u *ChatMessageUpdateOne) SetBody(v string) *ChatMessageUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableBody(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetSenderName sets the "sender_name" field.
func (_u *ChatMessageUpdateOne) SetSenderName(v string) *ChatMessageUpdateOne {
	_u.mutation.SetSenderName(v)
	return _u
}

// SetNillableSenderName sets the "sender_name" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableSenderName(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetSenderName(*v)
	}
	return _u
}

// SetRoomID sets the "room" edge to the ChatRoom entity by ID.
func (_u *ChatMessageUpdateOne) SetRoomID(id int) *ChatMessageUpdateOne {
	_u.mutation.SetRoomID(id)
	return _u
}

// SetRoom sets the "room" edge to the ChatRoom entity.
func (_u *ChatMessageUpdateOne) SetRoom(v *ChatRoom) *ChatMessageUpdateOne {
	return _u.SetRoomID(v.ID)
}

// SetSenderID sets the "sender" edge to the User entity by ID.
func (_u *ChatMessageUpdateOne) SetSenderID(id int) *ChatMessageUpdateOne {
	_u.mutation.SetSenderID(id)
	return _u
}

// SetNillableSenderID sets the "sender" edge to the User entity by ID if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableSenderID(id *int) *ChatMessageUpdateOne {
	if id != nil {
		_u = _u.SetSenderID(*id)
	}
	return _u
}

// SetSender sets the "sender" edge to the User entity.
func (_u *ChatMessageUpdateOne) SetSender(v *User) *ChatMessageUpdateOne {
	return _u.SetSenderID(v.ID)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_u *ChatMessageUpdateOne) Mutation() *ChatMessageMutation {
	return _u.mutation
}

// ClearRoom clears the "room" edge to the ChatRoom entity.
func (_u *ChatMessageUpdateOne) ClearRoom() *ChatMessageUpdateOne {
	_u.mutation.ClearRoom()
	return _u
}

// ClearSender clears the "sender" edge to the User entity.
func (_u *ChatMessageUpdateOne) ClearSender() *ChatMessageUpdateOne {
	_u.mutation.ClearSender()
	return _u
}

// Where appends a list predicates to the ChatMessageUpdate builder.
func (_u *ChatMessageUpdateOne) Where(ps ...predicate.ChatMessage) *ChatMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatMessageUpdateOne) Select(field string, fields ...string) *ChatMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatMessage entity.
func (_u *ChatMessageUpdateOne) Save(ctx context.Context) (*ChatMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageUpdateOne) SaveX(ctx context.Context) *ChatMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Body(); ok {
		if err := chatmessage.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SenderName(); ok {
		if err := chatmessage.SenderNameValidator(v); err != nil {
			return &ValidationError{Name: "sender_name", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.sender_name": %w`, err)}
		}
	}
	if _u.mutation.RoomCleared() && len(_u.mutation.RoomIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessage.room"`)
	}
	return nil
}

func (_u *ChatMessageUpdateOne) sqlSave(ctx context.Context) (_node *ChatMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessage.Table, chatmessage.Columns, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatmessage.FieldID)
		for _, f := range fields {
			if !chatmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(chatmessage.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.SenderName(); ok {
		_spec.SetField(chatmessage.FieldSenderName, field.TypeString, value)
	}
	if _u.mutation.RoomCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.RoomTable,
			Columns: []string{chatmessage.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.RoomTable,
			Columns: []string{chatmessage.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.SenderTable,
			Columns: []string{chatmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.SenderTable,
			Columns: []string{chatmessage.SenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
