// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/occult/pagode/ent/chatban"
	"github.com/occult/pagode/ent/chatroom"
	"github.com/occult/pagode/ent/user"
)

// ChatBanCreate is the builder for creating a ChatBan entity.
type ChatBanCreate struct {
	config
	mutation *ChatBanMutation
	hooks    []Hook
}

// SetIPHash sets the "ip_hash" field.
func (_c *ChatBanCreate) SetIPHash(v string) *ChatBanCreate {
	_c.mutation.SetIPHash(v)
	return _c
}

// SetNillableIPHash sets the "ip_hash" field if the given value is not nil.
func (_c *ChatBanCreate) SetNillableIPHash(v *string) *ChatBanCreate {
	if v != nil {
		_c.SetIPHash(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *ChatBanCreate) SetReason(v string) *ChatBanCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *ChatBanCreate) SetNillableReason(v *string) *ChatBanCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatBanCreate) SetCreatedAt(v time.Time) *ChatBanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatBanCreate) SetNillableCreatedAt(v *time.Time) *ChatBanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRoomID sets the "room" edge to the ChatRoom entity by ID.
func (_c *ChatBanCreate) SetRoomID(id int) *ChatBanCreate {
	_c.mutation.SetRoomID(id)
	return _c
}

// SetRoom sets the "room" edge to the ChatRoom entity.
func (_c *ChatBanCreate) SetRoom(v *ChatRoom) *ChatBanCreate {
	return _c.SetRoomID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *ChatBanCreate) SetUserID(id int) *ChatBanCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *ChatBanCreate) SetNillableUserID(id *int) *ChatBanCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChatBanCreate) SetUser(v *User) *ChatBanCreate {
	return _c.SetUserID(v.ID)
}

// SetBannedByUserID sets the "banned_by_user" edge to the User entity by ID.
func (_c *ChatBanCreate) SetBannedByUserID(id int) *ChatBanCreate {
	_c.mutation.SetBannedByUserID(id)
	return _c
}

// SetBannedByUser sets the "banned_by_user" edge to the User entity.
func (_c *ChatBanCreate) SetBannedByUser(v *User) *ChatBanCreate {
	return _c.SetBannedByUserID(v.ID)
}

// Mutation returns the ChatBanMutation object of the builder.
func (_c *ChatBanCreate) Mutation() *ChatBanMutation {
	return _c.mutation
}

// Save creates the ChatBan in the database.
func (_c *ChatBanCreate) Save(ctx context.Context) (*ChatBan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatBanCreate) SaveX(ctx context.Context) *ChatBan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatBanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatBanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatBanCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatban.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatBanCreate) check() error {
	if v, ok := _c.mutation.IPHash(); ok {
		if err := chatban.IPHashValidator(v); err != nil {
			return &ValidationError{Name: "ip_hash", err: fmt.Errorf(`ent: validator failed for field "ChatBan.ip_hash": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := chatban.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "ChatBan.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatBan.created_at"`)}
	}
	if len(_c.mutation.RoomIDs()) == 0 {
		return &ValidationError{Name: "room", err: errors.New(`ent: missing required edge "ChatBan.room"`)}
	}
	if len(_c.mutation.BannedByUserIDs()) == 0 {
		return &ValidationError{Name: "banned_by_user", err: errors.New(`ent: missing required edge "ChatBan.banned_by_user"`)}
	}
	return nil
}

func (_c *ChatBanCreate) sqlSave(ctx context.Context) (*ChatBan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatBanCreate) createSpec() (*ChatBan, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatBan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatban.Table, sqlgraph.NewFieldSpec(chatban.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.IPHash(); ok {
		_spec.SetField(chatban.FieldIPHash, field.TypeString, value)
		_node.IPHash = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(chatban.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatban.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatban.RoomTable,
			Columns: []string{chatban.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatroom.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.chat_room_bans = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatban.UserTable,
			Columns: []string{chatban.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_chat_bans = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BannedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatban.BannedByUserTable,
			Columns: []string{chatban.BannedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_chat_bans_issued = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatBanCreateBulk is the builder for creating many ChatBan entities in bulk.
type ChatBanCreateBulk struct {
	config
	err      error
	builders []*ChatBanCreate
}

// Save creates the ChatBan entities in the database.
func (_c *ChatBanCreateBulk) Save(ctx context.Context) ([]*ChatBan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatBan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatBanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatBanCreateBulk) SaveX(ctx context.Context) []*ChatBan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatBanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatBanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
