// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/occult/pagode/ent/paymentcustomer"
	"github.com/occult/pagode/ent/paymentintent"
	"github.com/occult/pagode/ent/paymentmethod"
	"github.com/occult/pagode/ent/predicate"
	"github.com/occult/pagode/ent/subscription"
	"github.com/occult/pagode/ent/user"
)

// PaymentCustomerQuery is the builder for querying PaymentCustomer entities.
type PaymentCustomerQuery struct {
	config
	ctx                *QueryContext
	order              []paymentcustomer.OrderOption
	inters             []Interceptor
	predicates         []predicate.PaymentCustomer
	withUser           *UserQuery
	withPaymentIntents *PaymentIntentQuery
	withSubscriptions  *SubscriptionQuery
	withPaymentMethods *PaymentMethodQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PaymentCustomerQuery builder.
func (_q *PaymentCustomerQuery) Where(ps ...predicate.PaymentCustomer) *PaymentCustomerQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PaymentCustomerQuery) Limit(limit int) *PaymentCustomerQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PaymentCustomerQuery) Offset(offset int) *PaymentCustomerQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PaymentCustomerQuery) Unique(unique bool) *PaymentCustomerQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PaymentCustomerQuery) Order(o ...paymentcustomer.OrderOption) *PaymentCustomerQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *PaymentCustomerQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(paymentcustomer.Table, paymentcustomer.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, paymentcustomer.UserTable, paymentcustomer.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPaymentIntents chains the current query on the "payment_intents" edge.
func (_q *PaymentCustomerQuery) QueryPaymentIntents() *PaymentIntentQuery {
	query := (&PaymentIntentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(paymentcustomer.Table, paymentcustomer.FieldID, selector),
			sqlgraph.To(paymentintent.Table, paymentintent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, paymentcustomer.PaymentIntentsTable, paymentcustomer.PaymentIntentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubscriptions chains the current query on the "subscriptions" edge.
func (_q *PaymentCustomerQuery) QuerySubscriptions() *SubscriptionQuery {
	query := (&SubscriptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(paymentcustomer.Table, paymentcustomer.FieldID, selector),
			sqlgraph.To(subscription.Table, subscription.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, paymentcustomer.SubscriptionsTable, paymentcustomer.SubscriptionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPaymentMethods chains the current query on the "payment_methods" edge.
func (_q *PaymentCustomerQuery) QueryPaymentMethods() *PaymentMethodQuery {
	query := (&PaymentMethodClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(paymentcustomer.Table, paymentcustomer.FieldID, selector),
			sqlgraph.To(paymentmethod.Table, paymentmethod.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, paymentcustomer.PaymentMethodsTable, paymentcustomer.PaymentMethodsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PaymentCustomer entity from the query.
// Returns a *NotFoundError when no PaymentCustomer was found.
func (_q *PaymentCustomerQuery) First(ctx context.Context) (*PaymentCustomer, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{paymentcustomer.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PaymentCustomerQuery) FirstX(ctx context.Context) *PaymentCustomer {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PaymentCustomer ID from the query.
// Returns a *NotFoundError when no PaymentCustomer ID was found.
func (_q *PaymentCustomerQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{paymentcustomer.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PaymentCustomerQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PaymentCustomer entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PaymentCustomer entity is found.
// Returns a *NotFoundError when no PaymentCustomer entities are found.
func (_q *PaymentCustomerQuery) Only(ctx context.Context) (*PaymentCustomer, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{paymentcustomer.Label}
	default:
		return nil, &NotSingularError{paymentcustomer.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PaymentCustomerQuery) OnlyX(ctx context.Context) *PaymentCustomer {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PaymentCustomer ID in the query.
// Returns a *NotSingularError when more than one PaymentCustomer ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PaymentCustomerQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{paymentcustomer.Label}
	default:
		err = &NotSingularError{paymentcustomer.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PaymentCustomerQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PaymentCustomers.
func (_q *PaymentCustomerQuery) All(ctx context.Context) ([]*PaymentCustomer, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PaymentCustomer, *PaymentCustomerQuery]()
	return withInterceptors[[]*PaymentCustomer](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PaymentCustomerQuery) AllX(ctx context.Context) []*PaymentCustomer {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PaymentCustomer IDs.
func (_q *PaymentCustomerQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(paymentcustomer.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PaymentCustomerQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PaymentCustomerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PaymentCustomerQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PaymentCustomerQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PaymentCustomerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PaymentCustomerQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PaymentCustomerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PaymentCustomerQuery) Clone() *PaymentCustomerQuery {
	if _q == nil {
		return nil
	}
	return &PaymentCustomerQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]paymentcustomer.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.PaymentCustomer{}, _q.predicates...),
		withUser:           _q.withUser.Clone(),
		withPaymentIntents: _q.withPaymentIntents.Clone(),
		withSubscriptions:  _q.withSubscriptions.Clone(),
		withPaymentMethods: _q.withPaymentMethods.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PaymentCustomerQuery) WithUser(opts ...func(*UserQuery)) *PaymentCustomerQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithPaymentIntents tells the query-builder to eager-load the nodes that are connected to
// the "payment_intents" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PaymentCustomerQuery) WithPaymentIntents(opts ...func(*PaymentIntentQuery)) *PaymentCustomerQuery {
	query := (&PaymentIntentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPaymentIntents = query
	return _q
}

// WithSubscriptions tells the query-builder to eager-load the nodes that are connected to
// the "subscriptions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PaymentCustomerQuery) WithSubscriptions(opts ...func(*SubscriptionQuery)) *PaymentCustomerQuery {
	query := (&SubscriptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSubscriptions = query
	return _q
}

// WithPaymentMethods tells the query-builder to eager-load the nodes that are connected to
// the "payment_methods" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PaymentCustomerQuery) WithPaymentMethods(opts ...func(*PaymentMethodQuery)) *PaymentCustomerQuery {
	query := (&PaymentMethodClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPaymentMethods = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProviderCustomerID string `json:"provider_customer_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PaymentCustomer.Query().
//		GroupBy(paymentcustomer.FieldProviderCustomerID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PaymentCustomerQuery) GroupBy(field string, fields ...string) *PaymentCustomerGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PaymentCustomerGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = paymentcustomer.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProviderCustomerID string `json:"provider_customer_id,omitempty"`
//	}
//
//	client.PaymentCustomer.Query().
//		Select(paymentcustomer.FieldProviderCustomerID).
//		Scan(ctx, &v)
func (_q *PaymentCustomerQuery) Select(fields ...string) *PaymentCustomerSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PaymentCustomerSelect{PaymentCustomerQuery: _q}
	sbuild.label = paymentcustomer.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PaymentCustomerSelect configured with the given aggregations.
func (_q *PaymentCustomerQuery) Aggregate(fns ...AggregateFunc) *PaymentCustomerSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PaymentCustomerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !paymentcustomer.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PaymentCustomerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PaymentCustomer, error) {
	var (
		nodes       = []*PaymentCustomer{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withUser != nil,
			_q.withPaymentIntents != nil,
			_q.withSubscriptions != nil,
			_q.withPaymentMethods != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PaymentCustomer).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PaymentCustomer{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *PaymentCustomer, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPaymentIntents; query != nil {
		if err := _q.loadPaymentIntents(ctx, query, nodes,
			func(n *PaymentCustomer) { n.Edges.PaymentIntents = []*PaymentIntent{} },
			func(n *PaymentCustomer, e *PaymentIntent) { n.Edges.PaymentIntents = append(n.Edges.PaymentIntents, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSubscriptions; query != nil {
		if err := _q.loadSubscriptions(ctx, query, nodes,
			func(n *PaymentCustomer) { n.Edges.Subscriptions = []*Subscription{} },
			func(n *PaymentCustomer, e *Subscription) { n.Edges.Subscriptions = append(n.Edges.Subscriptions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPaymentMethods; query != nil {
		if err := _q.loadPaymentMethods(ctx, query, nodes,
			func(n *PaymentCustomer) { n.Edges.PaymentMethods = []*PaymentMethod{} },
			func(n *PaymentCustomer, e *PaymentMethod) { n.Edges.PaymentMethods = append(n.Edges.PaymentMethods, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PaymentCustomerQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*PaymentCustomer, init func(*PaymentCustomer), assign func(*PaymentCustomer, *User)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*PaymentCustomer)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.User(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(paymentcustomer.UserColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.payment_customer_user
		if fk == nil {
			return fmt.Errorf(`foreign-key "payment_customer_user" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "payment_customer_user" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PaymentCustomerQuery) loadPaymentIntents(ctx context.Context, query *PaymentIntentQuery, nodes []*PaymentCustomer, init func(*PaymentCustomer), assign func(*PaymentCustomer, *PaymentIntent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*PaymentCustomer)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.PaymentIntent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(paymentcustomer.PaymentIntentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.payment_customer_payment_intents
		if fk == nil {
			return fmt.Errorf(`foreign-key "payment_customer_payment_intents" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "payment_customer_payment_intents" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PaymentCustomerQuery) loadSubscriptions(ctx context.Context, query *SubscriptionQuery, nodes []*PaymentCustomer, init func(*PaymentCustomer), assign func(*PaymentCustomer, *Subscription)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*PaymentCustomer)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Subscription(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(paymentcustomer.SubscriptionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.payment_customer_subscriptions
		if fk == nil {
			return fmt.Errorf(`foreign-key "payment_customer_subscriptions" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "payment_customer_subscriptions" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PaymentCustomerQuery) loadPaymentMethods(ctx context.Context, query *PaymentMethodQuery, nodes []*PaymentCustomer, init func(*PaymentCustomer), assign func(*PaymentCustomer, *PaymentMethod)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*PaymentCustomer)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.PaymentMethod(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(paymentcustomer.PaymentMethodsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.payment_customer_payment_methods
		if fk == nil {
			return fmt.Errorf(`foreign-key "payment_customer_payment_methods" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "payment_customer_payment_methods" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *PaymentCustomerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PaymentCustomerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(paymentcustomer.Table, paymentcustomer.Columns, sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentcustomer.FieldID)
		for i := range fields {
			if fields[i] != paymentcustomer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PaymentCustomerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(paymentcustomer.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = paymentcustomer.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PaymentCustomerGroupBy is the group-by builder for PaymentCustomer entities.
type PaymentCustomerGroupBy struct {
	selector
	build *PaymentCustomerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PaymentCustomerGroupBy) Aggregate(fns ...AggregateFunc) *PaymentCustomerGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PaymentCustomerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PaymentCustomerQuery, *PaymentCustomerGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PaymentCustomerGroupBy) sqlScan(ctx context.Context, root *PaymentCustomerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PaymentCustomerSelect is the builder for selecting fields of PaymentCustomer entities.
type PaymentCustomerSelect struct {
	*PaymentCustomerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PaymentCustomerSelect) Aggregate(fns ...AggregateFunc) *PaymentCustomerSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PaymentCustomerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PaymentCustomerQuery, *PaymentCustomerSelect](ctx, _s.PaymentCustomerQuery, _s, _s.inters, v)
}

func (_s *PaymentCustomerSelect) sqlScan(ctx context.Context, root *PaymentCustomerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
