// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/occult/pagode/ent/paymentcustomer"
	"github.com/occult/pagode/ent/paymentintent"
	"github.com/occult/pagode/ent/paymentmethod"
	"github.com/occult/pagode/ent/predicate"
	"github.com/occult/pagode/ent/subscription"
	"github.com/occult/pagode/ent/user"
)

// PaymentCustomerUpdate is the builder for updating PaymentCustomer entities.
type PaymentCustomerUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentCustomerMutation
}

// Where appends a list predicates to the PaymentCustomerUpdate builder.
func (_u *PaymentCustomerUpdate) Where(ps ...predicate.PaymentCustomer) *PaymentCustomerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderCustomerID sets the "provider_customer_id" field.
func (_u *PaymentCustomerUpdate) SetProviderCustomerID(v string) *PaymentCustomerUpdate {
	_u.mutation.SetProviderCustomerID(v)
	return _u
}

// SetNillableProviderCustomerID sets the "provider_customer_id" field if the given value is not nil.
func (_u *PaymentCustomerUpdate) SetNillableProviderCustomerID(v *string) *PaymentCustomerUpdate {
	if v != nil {
		_u.SetProviderCustomerID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentCustomerUpdate) SetProvider(v string) *PaymentCustomerUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentCustomerUpdate) SetNillableProvider(v *string) *PaymentCustomerUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *PaymentCustomerUpdate) SetEmail(v string) *PaymentCustomerUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *PaymentCustomerUpdate) SetNillableEmail(v *string) *PaymentCustomerUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PaymentCustomerUpdate) SetName(v string) *PaymentCustomerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PaymentCustomerUpdate) SetNillableName(v *string) *PaymentCustomerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *PaymentCustomerUpdate) ClearName() *PaymentCustomerUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PaymentCustomerUpdate) SetMetadata(v map[string]interface{}) *PaymentCustomerUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *PaymentCustomerUpdate) ClearMetadata() *PaymentCustomerUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentCustomerUpdate) SetUpdatedAt(v time.Time) *PaymentCustomerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PaymentCustomerUpdate) SetUserID(id int) *PaymentCustomerUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentCustomerUpdate) SetUser(v *User) *PaymentCustomerUpdate {
	return _u.SetUserID(v.ID)
}

// AddPaymentIntentIDs adds the "payment_intents" edge to the PaymentIntent entity by IDs.
func (_u *PaymentCustomerUpdate) AddPaymentIntentIDs(ids ...int) *PaymentCustomerUpdate {
	_u.mutation.AddPaymentIntentIDs(ids...)
	return _u
}

// AddPaymentIntents adds the "payment_intents" edges to the PaymentIntent entity.
func (_u *PaymentCustomerUpdate) AddPaymentIntents(v ...*PaymentIntent) *PaymentCustomerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentIntentIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (_u *PaymentCustomerUpdate) AddSubscriptionIDs(ids ...int) *PaymentCustomerUpdate {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (_u *PaymentCustomerUpdate) AddSubscriptions(v ...*Subscription) *PaymentCustomerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddPaymentMethodIDs adds the "payment_methods" edge to the PaymentMethod entity by IDs.
func (_u *PaymentCustomerUpdate) AddPaymentMethodIDs(ids ...int) *PaymentCustomerUpdate {
	_u.mutation.AddPaymentMethodIDs(ids...)
	return _u
}

// AddPaymentMethods adds the "payment_methods" edges to the PaymentMethod entity.
func (_u *PaymentCustomerUpdate) AddPaymentMethods(v ...*PaymentMethod) *PaymentCustomerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentMethodIDs(ids...)
}

// Mutation returns the PaymentCustomerMutation object of the builder.
func (_u *PaymentCustomerUpdate) Mutation() *PaymentCustomerMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentCustomerUpdate) ClearUser() *PaymentCustomerUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearPaymentIntents clears all "payment_intents" edges to the PaymentIntent entity.
func (_u *PaymentCustomerUpdate) ClearPaymentIntents() *PaymentCustomerUpdate {
	_u.mutation.ClearPaymentIntents()
	return _u
}

// RemovePaymentIntentIDs removes the "payment_intents" edge to PaymentIntent entities by IDs.
func (_u *PaymentCustomerUpdate) RemovePaymentIntentIDs(ids ...int) *PaymentCustomerUpdate {
	_u.mutation.RemovePaymentIntentIDs(ids...)
	return _u
}

// RemovePaymentIntents removes "payment_intents" edges to PaymentIntent entities.
func (_u *PaymentCustomerUpdate) RemovePaymentIntents(v ...*PaymentIntent) *PaymentCustomerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentIntentIDs(ids...)
}

// ClearSubscriptions clears all "subscriptions" edges to the Subscription entity.
func (_u *PaymentCustomerUpdate) ClearSubscriptions() *PaymentCustomerUpdate {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to Subscription entities by IDs.
func (_u *PaymentCustomerUpdate) RemoveSubscriptionIDs(ids ...int) *PaymentCustomerUpdate {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to Subscription entities.
func (_u *PaymentCustomerUpdate) RemoveSubscriptions(v ...*Subscription) *PaymentCustomerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearPaymentMethods clears all "payment_methods" edges to the PaymentMethod entity.
func (_u *PaymentCustomerUpdate) ClearPaymentMethods() *PaymentCustomerUpdate {
	_u.mutation.ClearPaymentMethods()
	return _u
}

// RemovePaymentMethodIDs removes the "payment_methods" edge to PaymentMethod entities by IDs.
func (_u *PaymentCustomerUpdate) RemovePaymentMethodIDs(ids ...int) *PaymentCustomerUpdate {
	_u.mutation.RemovePaymentMethodIDs(ids...)
	return _u
}

// RemovePaymentMethods removes "payment_methods" edges to PaymentMethod entities.
func (_u *PaymentCustomerUpdate) RemovePaymentMethods(v ...*PaymentMethod) *PaymentCustomerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentMethodIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentCustomerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentCustomerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentCustomerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentCustomerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentCustomerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentcustomer.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentCustomerUpdate) check() error {
	if v, ok := _u.mutation.ProviderCustomerID(); ok {
		if err := paymentcustomer.ProviderCustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_customer_id", err: fmt.Errorf(`ent: validator failed for field "PaymentCustomer.provider_customer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentcustomer.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentCustomer.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := paymentcustomer.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "PaymentCustomer.email": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentCustomer.user"`)
	}
	return nil
}

func (_u *PaymentCustomerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentcustomer.Table, paymentcustomer.Columns, sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderCustomerID(); ok {
		_spec.SetField(paymentcustomer.FieldProviderCustomerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentcustomer.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(paymentcustomer.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(paymentcustomer.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(paymentcustomer.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(paymentcustomer.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(paymentcustomer.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentcustomer.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   paymentcustomer.UserTable,
			Columns: []string{paymentcustomer.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   paymentcustomer.UserTable,
			Columns: []string{paymentcustomer.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentIntentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.PaymentIntentsTable,
			Columns: []string{paymentcustomer.PaymentIntentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentintent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentIntentsIDs(); len(nodes) > 0 && !_u.mutation.PaymentIntentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.PaymentIntentsTable,
			Columns: []string{paymentcustomer.PaymentIntentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentintent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentIntentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.PaymentIntentsTable,
			Columns: []string{paymentcustomer.PaymentIntentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentintent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.SubscriptionsTable,
			Columns: []string{paymentcustomer.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.SubscriptionsTable,
			Columns: []string{paymentcustomer.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.SubscriptionsTable,
			Columns: []string{paymentcustomer.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentMethodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.PaymentMethodsTable,
			Columns: []string{paymentcustomer.PaymentMethodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentmethod.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentMethodsIDs(); len(nodes) > 0 && !_u.mutation.PaymentMethodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.PaymentMethodsTable,
			Columns: []string{paymentcustomer.PaymentMethodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentmethod.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentMethodsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.PaymentMethodsTable,
			Columns: []string{paymentcustomer.PaymentMethodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentmethod.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentcustomer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentCustomerUpdateOne is the builder for updating a single PaymentCustomer entity.
type PaymentCustomerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentCustomerMutation
}

// SetProviderCustomerID sets the "provider_customer_id" field.
func (_u *PaymentCustomerUpdateOne) SetProviderCustomerID(v string) *PaymentCustomerUpdateOne {
	_u.mutation.SetProviderCustomerID(v)
	return _u
}

// SetNillableProviderCustomerID sets the "provider_customer_id" field if the given value is not nil.
func (_u *PaymentCustomerUpdateOne) SetNillableProviderCustomerID(v *string) *PaymentCustomerUpdateOne {
	if v != nil {
		_u.SetProviderCustomerID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentCustomerUpdateOne) SetProvider(v string) *PaymentCustomerUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentCustomerUpdateOne) SetNillableProvider(v *string) *PaymentCustomerUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *PaymentCustomerUpdateOne) SetEmail(v string) *PaymentCustomerUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *PaymentCustomerUpdateOne) SetNillableEmail(v *string) *PaymentCustomerUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PaymentCustomerUpdateOne) SetName(v string) *PaymentCustomerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PaymentCustomerUpdateOne) SetNillableName(v *string) *PaymentCustomerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *PaymentCustomerUpdateOne) ClearName() *PaymentCustomerUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PaymentCustomerUpdateOne) SetMetadata(v map[string]interface{}) *PaymentCustomerUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *PaymentCustomerUpdateOne) ClearMetadata() *PaymentCustomerUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentCustomerUpdateOne) SetUpdatedAt(v time.Time) *PaymentCustomerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *PaymentCustomerUpdateOne) SetUserID(id int) *PaymentCustomerUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentCustomerUpdateOne) SetUser(v *User) *PaymentCustomerUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddPaymentIntentIDs adds the "payment_intents" edge to the PaymentIntent entity by IDs.
func (_u *PaymentCustomerUpdateOne) AddPaymentIntentIDs(ids ...int) *PaymentCustomerUpdateOne {
	_u.mutation.AddPaymentIntentIDs(ids...)
	return _u
}

// AddPaymentIntents adds the "payment_intents" edges to the PaymentIntent entity.
func (_u *PaymentCustomerUpdateOne) AddPaymentIntents(v ...*PaymentIntent) *PaymentCustomerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentIntentIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (_u *PaymentCustomerUpdateOne) AddSubscriptionIDs(ids ...int) *PaymentCustomerUpdateOne {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (_u *PaymentCustomerUpdateOne) AddSubscriptions(v ...*Subscription) *PaymentCustomerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddPaymentMethodIDs adds the "payment_methods" edge to the PaymentMethod entity by IDs.
func (_u *PaymentCustomerUpdateOne) AddPaymentMethodIDs(ids ...int) *PaymentCustomerUpdateOne {
	_u.mutation.AddPaymentMethodIDs(ids...)
	return _u
}

// AddPaymentMethods adds the "payment_methods" edges to the PaymentMethod entity.
func (_u *PaymentCustomerUpdateOne) AddPaymentMethods(v ...*PaymentMethod) *PaymentCustomerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentMethodIDs(ids...)
}

// Mutation returns the PaymentCustomerMutation object of the builder.
func (_u *PaymentCustomerUpdateOne) Mutation() *PaymentCustomerMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentCustomerUpdateOne) ClearUser() *PaymentCustomerUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearPaymentIntents clears all "payment_intents" edges to the PaymentIntent entity.
func (_u *PaymentCustomerUpdateOne) ClearPaymentIntents() *PaymentCustomerUpdateOne {
	_u.mutation.ClearPaymentIntents()
	return _u
}

// RemovePaymentIntentIDs removes the "payment_intents" edge to PaymentIntent entities by IDs.
func (_u *PaymentCustomerUpdateOne) RemovePaymentIntentIDs(ids ...int) *PaymentCustomerUpdateOne {
	_u.mutation.RemovePaymentIntentIDs(ids...)
	return _u
}

// RemovePaymentIntents removes "payment_intents" edges to PaymentIntent entities.
func (_u *PaymentCustomerUpdateOne) RemovePaymentIntents(v ...*PaymentIntent) *PaymentCustomerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentIntentIDs(ids...)
}

// ClearSubscriptions clears all "subscriptions" edges to the Subscription entity.
func (_u *PaymentCustomerUpdateOne) ClearSubscriptions() *PaymentCustomerUpdateOne {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to Subscription entities by IDs.
func (_u *PaymentCustomerUpdateOne) RemoveSubscriptionIDs(ids ...int) *PaymentCustomerUpdateOne {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to Subscription entities.
func (_u *PaymentCustomerUpdateOne) RemoveSubscriptions(v ...*Subscription) *PaymentCustomerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearPaymentMethods clears all "payment_methods" edges to the PaymentMethod entity.
func (_u *PaymentCustomerUpdateOne) ClearPaymentMethods() *PaymentCustomerUpdateOne {
	_u.mutation.ClearPaymentMethods()
	return _u
}

// RemovePaymentMethodIDs removes the "payment_methods" edge to PaymentMethod entities by IDs.
func (_u *PaymentCustomerUpdateOne) RemovePaymentMethodIDs(ids ...int) *PaymentCustomerUpdateOne {
	_u.mutation.RemovePaymentMethodIDs(ids...)
	return _u
}

// RemovePaymentMethods removes "payment_methods" edges to PaymentMethod entities.
func (_u *PaymentCustomerUpdateOne) RemovePaymentMethods(v ...*PaymentMethod) *PaymentCustomerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentMethodIDs(ids...)
}

// Where appends a list predicates to the PaymentCustomerUpdate builder.
func (_u *PaymentCustomerUpdateOne) Where(ps ...predicate.PaymentCustomer) *PaymentCustomerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentCustomerUpdateOne) Select(field string, fields ...string) *PaymentCustomerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentCustomer entity.
func (_u *PaymentCustomerUpdateOne) Save(ctx context.Context) (*PaymentCustomer, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentCustomerUpdateOne) SaveX(ctx context.Context) *PaymentCustomer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentCustomerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentCustomerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentCustomerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentcustomer.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentCustomerUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderCustomerID(); ok {
		if err := paymentcustomer.ProviderCustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_customer_id", err: fmt.Errorf(`ent: validator failed for field "PaymentCustomer.provider_customer_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentcustomer.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentCustomer.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := paymentcustomer.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "PaymentCustomer.email": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentCustomer.user"`)
	}
	return nil
}

func (_u *PaymentCustomerUpdateOne) sqlSave(ctx context.Context) (_node *PaymentCustomer, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentcustomer.Table, paymentcustomer.Columns, sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentCustomer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentcustomer.FieldID)
		for _, f := range fields {
			if !paymentcustomer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentcustomer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderCustomerID(); ok {
		_spec.SetField(paymentcustomer.FieldProviderCustomerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentcustomer.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(paymentcustomer.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(paymentcustomer.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(paymentcustomer.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(paymentcustomer.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(paymentcustomer.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentcustomer.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   paymentcustomer.UserTable,
			Columns: []string{paymentcustomer.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   paymentcustomer.UserTable,
			Columns: []string{paymentcustomer.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentIntentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.PaymentIntentsTable,
			Columns: []string{paymentcustomer.PaymentIntentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentintent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentIntentsIDs(); len(nodes) > 0 && !_u.mutation.PaymentIntentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.PaymentIntentsTable,
			Columns: []string{paymentcustomer.PaymentIntentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentintent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentIntentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.PaymentIntentsTable,
			Columns: []string{paymentcustomer.PaymentIntentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentintent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.SubscriptionsTable,
			Columns: []string{paymentcustomer.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.SubscriptionsTable,
			Columns: []string{paymentcustomer.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.SubscriptionsTable,
			Columns: []string{paymentcustomer.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentMethodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.PaymentMethodsTable,
			Columns: []string{paymentcustomer.PaymentMethodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentmethod.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentMethodsIDs(); len(nodes) > 0 && !_u.mutation.PaymentMethodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.PaymentMethodsTable,
			Columns: []string{paymentcustomer.PaymentMethodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentmethod.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentMethodsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paymentcustomer.PaymentMethodsTable,
			Columns: []string{paymentcustomer.PaymentMethodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentmethod.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentCustomer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentcustomer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
