// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/occult/pagode/ent/paymentcustomer"
	"github.com/occult/pagode/ent/paymentmethod"
	"github.com/occult/pagode/ent/predicate"
)

// PaymentMethodUpdate is the builder for updating PaymentMethod entities.
type PaymentMethodUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMethodMutation
}

// Where appends a list predicates to the PaymentMethodUpdate builder.
func (_u *PaymentMethodUpdate) Where(ps ...predicate.PaymentMethod) *PaymentMethodUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderPaymentMethodID sets the "provider_payment_method_id" field.
func (_u *PaymentMethodUpdate) SetProviderPaymentMethodID(v string) *PaymentMethodUpdate {
	_u.mutation.SetProviderPaymentMethodID(v)
	return _u
}

// SetNillableProviderPaymentMethodID sets the "provider_payment_method_id" field if the given value is not nil.
func (_u *PaymentMethodUpdate) SetNillableProviderPaymentMethodID(v *string) *PaymentMethodUpdate {
	if v != nil {
		_u.SetProviderPaymentMethodID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentMethodUpdate) SetProvider(v string) *PaymentMethodUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentMethodUpdate) SetNillableProvider(v *string) *PaymentMethodUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *PaymentMethodUpdate) SetType(v paymentmethod.Type) *PaymentMethodUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PaymentMethodUpdate) SetNillableType(v *paymentmethod.Type) *PaymentMethodUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetLastFour sets the "last_four" field.
func (_u *PaymentMethodUpdate) SetLastFour(v string) *PaymentMethodUpdate {
	_u.mutation.SetLastFour(v)
	return _u
}

// SetNillableLastFour sets the "last_four" field if the given value is not nil.
func (_u *PaymentMethodUpdate) SetNillableLastFour(v *string) *PaymentMethodUpdate {
	if v != nil {
		_u.SetLastFour(*v)
	}
	return _u
}

// ClearLastFour clears the value of the "last_four" field.
func (_u *PaymentMethodUpdate) ClearLastFour() *PaymentMethodUpdate {
	_u.mutation.ClearLastFour()
	return _u
}

// SetBrand sets the "brand" field.
func (_u *PaymentMethodUpdate) SetBrand(v string) *PaymentMethodUpdate {
	_u.mutation.SetBrand(v)
	return _u
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (_u *PaymentMethodUpdate) SetNillableBrand(v *string) *PaymentMethodUpdate {
	if v != nil {
		_u.SetBrand(*v)
	}
	return _u
}

// ClearBrand clears the value of the "brand" field.
func (_u *PaymentMethodUpdate) ClearBrand() *PaymentMethodUpdate {
	_u.mutation.ClearBrand()
	return _u
}

// SetExpMonth sets the "exp_month" field.
func (_u *PaymentMethodUpdate) SetExpMonth(v int) *PaymentMethodUpdate {
	_u.mutation.ResetExpMonth()
	_u.mutation.SetExpMonth(v)
	return _u
}

// SetNillableExpMonth sets the "exp_month" field if the given value is not nil.
func (_u *PaymentMethodUpdate) SetNillableExpMonth(v *int) *PaymentMethodUpdate {
	if v != nil {
		_u.SetExpMonth(*v)
	}
	return _u
}

// AddExpMonth adds value to the "exp_month" field.
func (_u *PaymentMethodUpdate) AddExpMonth(v int) *PaymentMethodUpdate {
	_u.mutation.AddExpMonth(v)
	return _u
}

// ClearExpMonth clears the value of the "exp_month" field.
func (_u *PaymentMethodUpdate) ClearExpMonth() *PaymentMethodUpdate {
	_u.mutation.ClearExpMonth()
	return _u
}

// SetExpYear sets the "exp_year" field.
func (_u *PaymentMethodUpdate) SetExpYear(v int) *PaymentMethodUpdate {
	_u.mutation.ResetExpYear()
	_u.mutation.SetExpYear(v)
	return _u
}

// SetNillableExpYear sets the "exp_year" field if the given value is not nil.
func (_u *PaymentMethodUpdate) SetNillableExpYear(v *int) *PaymentMethodUpdate {
	if v != nil {
		_u.SetExpYear(*v)
	}
	return _u
}

// AddExpYear adds value to the "exp_year" field.
func (_u *PaymentMethodUpdate) AddExpYear(v int) *PaymentMethodUpdate {
	_u.mutation.AddExpYear(v)
	return _u
}

// ClearExpYear clears the value of the "exp_year" field.
func (_u *PaymentMethodUpdate) ClearExpYear() *PaymentMethodUpdate {
	_u.mutation.ClearExpYear()
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *PaymentMethodUpdate) SetIsDefault(v bool) *PaymentMethodUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *PaymentMethodUpdate) SetNillableIsDefault(v *bool) *PaymentMethodUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PaymentMethodUpdate) SetMetadata(v map[string]interface{}) *PaymentMethodUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *PaymentMethodUpdate) ClearMetadata() *PaymentMethodUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentMethodUpdate) SetUpdatedAt(v time.Time) *PaymentMethodUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCustomerID sets the "customer" edge to the PaymentCustomer entity by ID.
func (_u *PaymentMethodUpdate) SetCustomerID(id int) *PaymentMethodUpdate {
	_u.mutation.SetCustomerID(id)
	return _u
}

// SetCustomer sets the "customer" edge to the PaymentCustomer entity.
func (_u *PaymentMethodUpdate) SetCustomer(v *PaymentCustomer) *PaymentMethodUpdate {
	return _u.SetCustomerID(v.ID)
}

// Mutation returns the PaymentMethodMutation object of the builder.
func (_u *PaymentMethodUpdate) Mutation() *PaymentMethodMutation {
	return _u.mutation
}

// ClearCustomer clears the "customer" edge to the PaymentCustomer entity.
func (_u *PaymentMethodUpdate) ClearCustomer() *PaymentMethodUpdate {
	_u.mutation.ClearCustomer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentMethodUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentMethodUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentMethodUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentMethodUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentMethodUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentmethod.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentMethodUpdate) check() error {
	if v, ok := _u.mutation.ProviderPaymentMethodID(); ok {
		if err := paymentmethod.ProviderPaymentMethodIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_payment_method_id", err: fmt.Errorf(`ent: validator failed for field "PaymentMethod.provider_payment_method_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentmethod.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentMethod.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := paymentmethod.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "PaymentMethod.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpMonth(); ok {
		if err := paymentmethod.ExpMonthValidator(v); err != nil {
			return &ValidationError{Name: "exp_month", err: fmt.Errorf(`ent: validator failed for field "PaymentMethod.exp_month": %w`, err)}
		}
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentMethod.customer"`)
	}
	return nil
}

func (_u *PaymentMethodUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentmethod.Table, paymentmethod.Columns, sqlgraph.NewFieldSpec(paymentmethod.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderPaymentMethodID(); ok {
		_spec.SetField(paymentmethod.FieldProviderPaymentMethodID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentmethod.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(paymentmethod.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastFour(); ok {
		_spec.SetField(paymentmethod.FieldLastFour, field.TypeString, value)
	}
	if _u.mutation.LastFourCleared() {
		_spec.ClearField(paymentmethod.FieldLastFour, field.TypeString)
	}
	if value, ok := _u.mutation.Brand(); ok {
		_spec.SetField(paymentmethod.FieldBrand, field.TypeString, value)
	}
	if _u.mutation.BrandCleared() {
		_spec.ClearField(paymentmethod.FieldBrand, field.TypeString)
	}
	if value, ok := _u.mutation.ExpMonth(); ok {
		_spec.SetField(paymentmethod.FieldExpMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpMonth(); ok {
		_spec.AddField(paymentmethod.FieldExpMonth, field.TypeInt, value)
	}
	if _u.mutation.ExpMonthCleared() {
		_spec.ClearField(paymentmethod.FieldExpMonth, field.TypeInt)
	}
	if value, ok := _u.mutation.ExpYear(); ok {
		_spec.SetField(paymentmethod.FieldExpYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpYear(); ok {
		_spec.AddField(paymentmethod.FieldExpYear, field.TypeInt, value)
	}
	if _u.mutation.ExpYearCleared() {
		_spec.ClearField(paymentmethod.FieldExpYear, field.TypeInt)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(paymentmethod.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(paymentmethod.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(paymentmethod.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentmethod.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentmethod.CustomerTable,
			Columns: []string{paymentmethod.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentmethod.CustomerTable,
			Columns: []string{paymentmethod.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentmethod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentMethodUpdateOne is the builder for updating a single PaymentMethod entity.
type PaymentMethodUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMethodMutation
}

// SetProviderPaymentMethodID sets the "provider_payment_method_id" field.
func (_u *PaymentMethodUpdateOne) SetProviderPaymentMethodID(v string) *PaymentMethodUpdateOne {
	_u.mutation.SetProviderPaymentMethodID(v)
	return _u
}

// SetNillableProviderPaymentMethodID sets the "provider_payment_method_id" field if the given value is not nil.
func (_u *PaymentMethodUpdateOne) SetNillableProviderPaymentMethodID(v *string) *PaymentMethodUpdateOne {
	if v != nil {
		_u.SetProviderPaymentMethodID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentMethodUpdateOne) SetProvider(v string) *PaymentMethodUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentMethodUpdateOne) SetNillableProvider(v *string) *PaymentMethodUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *PaymentMethodUpdateOne) SetType(v paymentmethod.Type) *PaymentMethodUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PaymentMethodUpdateOne) SetNillableType(v *paymentmethod.Type) *PaymentMethodUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetLastFour sets the "last_four" field.
func (_u *PaymentMethodUpdateOne) SetLastFour(v string) *PaymentMethodUpdateOne {
	_u.mutation.SetLastFour(v)
	return _u
}

// SetNillableLastFour sets the "last_four" field if the given value is not nil.
func (_u *PaymentMethodUpdateOne) SetNillableLastFour(v *string) *PaymentMethodUpdateOne {
	if v != nil {
		_u.SetLastFour(*v)
	}
	return _u
}

// ClearLastFour clears the value of the "last_four" field.
func (_u *PaymentMethodUpdateOne) ClearLastFour() *PaymentMethodUpdateOne {
	_u.mutation.ClearLastFour()
	return _u
}

// SetBrand sets the "brand" field.
func (_u *PaymentMethodUpdateOne) SetBrand(v string) *PaymentMethodUpdateOne {
	_u.mutation.SetBrand(v)
	return _u
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (_u *PaymentMethodUpdateOne) SetNillableBrand(v *string) *PaymentMethodUpdateOne {
	if v != nil {
		_u.SetBrand(*v)
	}
	return _u
}

// ClearBrand clears the value of the "brand" field.
func (_u *PaymentMethodUpdateOne) ClearBrand() *PaymentMethodUpdateOne {
	_u.mutation.ClearBrand()
	return _u
}

// SetExpMonth sets the "exp_month" field.
func (_u *PaymentMethodUpdateOne) SetExpMonth(v int) *PaymentMethodUpdateOne {
	_u.mutation.ResetExpMonth()
	_u.mutation.SetExpMonth(v)
	return _u
}

// SetNillableExpMonth sets the "exp_month" field if the given value is not nil.
func (_u *PaymentMethodUpdateOne) SetNillableExpMonth(v *int) *PaymentMethodUpdateOne {
	if v != nil {
		_u.SetExpMonth(*v)
	}
	return _u
}

// AddExpMonth adds value to the "exp_month" field.
func (_u *PaymentMethodUpdateOne) AddExpMonth(v int) *PaymentMethodUpdateOne {
	_u.mutation.AddExpMonth(v)
	return _u
}

// ClearExpMonth clears the value of the "exp_month" field.
func (_u *PaymentMethodUpdateOne) ClearExpMonth() *PaymentMethodUpdateOne {
	_u.mutation.ClearExpMonth()
	return _u
}

// SetExpYear sets the "exp_year" field.
func (_u *PaymentMethodUpdateOne) SetExpYear(v int) *PaymentMethodUpdateOne {
	_u.mutation.ResetExpYear()
	_u.mutation.SetExpYear(v)
	return _u
}

// SetNillableExpYear sets the "exp_year" field if the given value is not nil.
func (_u *PaymentMethodUpdateOne) SetNillableExpYear(v *int) *PaymentMethodUpdateOne {
	if v != nil {
		_u.SetExpYear(*v)
	}
	return _u
}

// AddExpYear adds value to the "exp_year" field.
func (_u *PaymentMethodUpdateOne) AddExpYear(v int) *PaymentMethodUpdateOne {
	_u.mutation.AddExpYear(v)
	return _u
}

// ClearExpYear clears the value of the "exp_year" field.
func (_u *PaymentMethodUpdateOne) ClearExpYear() *PaymentMethodUpdateOne {
	_u.mutation.ClearExpYear()
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *PaymentMethodUpdateOne) SetIsDefault(v bool) *PaymentMethodUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *PaymentMethodUpdateOne) SetNillableIsDefault(v *bool) *PaymentMethodUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PaymentMethodUpdateOne) SetMetadata(v map[string]interface{}) *PaymentMethodUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *PaymentMethodUpdateOne) ClearMetadata() *PaymentMethodUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentMethodUpdateOne) SetUpdatedAt(v time.Time) *PaymentMethodUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCustomerID sets the "customer" edge to the PaymentCustomer entity by ID.
func (_u *PaymentMethodUpdateOne) SetCustomerID(id int) *PaymentMethodUpdateOne {
	_u.mutation.SetCustomerID(id)
	return _u
}

// SetCustomer sets the "customer" edge to the PaymentCustomer entity.
func (_u *PaymentMethodUpdateOne) SetCustomer(v *PaymentCustomer) *PaymentMethodUpdateOne {
	return _u.SetCustomerID(v.ID)
}

// Mutation returns the PaymentMethodMutation object of the builder.
func (_u *PaymentMethodUpdateOne) Mutation() *PaymentMethodMutation {
	return _u.mutation
}

// ClearCustomer clears the "customer" edge to the PaymentCustomer entity.
func (_u *PaymentMethodUpdateOne) ClearCustomer() *PaymentMethodUpdateOne {
	_u.mutation.ClearCustomer()
	return _u
}

// Where appends a list predicates to the PaymentMethodUpdate builder.
func (_u *PaymentMethodUpdateOne) Where(ps ...predicate.PaymentMethod) *PaymentMethodUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentMethodUpdateOne) Select(field string, fields ...string) *PaymentMethodUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentMethod entity.
func (_u *PaymentMethodUpdateOne) Save(ctx context.Context) (*PaymentMethod, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentMethodUpdateOne) SaveX(ctx context.Context) *PaymentMethod {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentMethodUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentMethodUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentMethodUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentmethod.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentMethodUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderPaymentMethodID(); ok {
		if err := paymentmethod.ProviderPaymentMethodIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_payment_method_id", err: fmt.Errorf(`ent: validator failed for field "PaymentMethod.provider_payment_method_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentmethod.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentMethod.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := paymentmethod.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "PaymentMethod.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExpMonth(); ok {
		if err := paymentmethod.ExpMonthValidator(v); err != nil {
			return &ValidationError{Name: "exp_month", err: fmt.Errorf(`ent: validator failed for field "PaymentMethod.exp_month": %w`, err)}
		}
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentMethod.customer"`)
	}
	return nil
}

func (_u *PaymentMethodUpdateOne) sqlSave(ctx context.Context) (_node *PaymentMethod, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentmethod.Table, paymentmethod.Columns, sqlgraph.NewFieldSpec(paymentmethod.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentMethod.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentmethod.FieldID)
		for _, f := range fields {
			if !paymentmethod.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentmethod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderPaymentMethodID(); ok {
		_spec.SetField(paymentmethod.FieldProviderPaymentMethodID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentmethod.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(paymentmethod.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastFour(); ok {
		_spec.SetField(paymentmethod.FieldLastFour, field.TypeString, value)
	}
	if _u.mutation.LastFourCleared() {
		_spec.ClearField(paymentmethod.FieldLastFour, field.TypeString)
	}
	if value, ok := _u.mutation.Brand(); ok {
		_spec.SetField(paymentmethod.FieldBrand, field.TypeString, value)
	}
	if _u.mutation.BrandCleared() {
		_spec.ClearField(paymentmethod.FieldBrand, field.TypeString)
	}
	if value, ok := _u.mutation.ExpMonth(); ok {
		_spec.SetField(paymentmethod.FieldExpMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpMonth(); ok {
		_spec.AddField(paymentmethod.FieldExpMonth, field.TypeInt, value)
	}
	if _u.mutation.ExpMonthCleared() {
		_spec.ClearField(paymentmethod.FieldExpMonth, field.TypeInt)
	}
	if value, ok := _u.mutation.ExpYear(); ok {
		_spec.SetField(paymentmethod.FieldExpYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpYear(); ok {
		_spec.AddField(paymentmethod.FieldExpYear, field.TypeInt, value)
	}
	if _u.mutation.ExpYearCleared() {
		_spec.ClearField(paymentmethod.FieldExpYear, field.TypeInt)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(paymentmethod.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(paymentmethod.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(paymentmethod.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentmethod.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentmethod.CustomerTable,
			Columns: []string{paymentmethod.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentmethod.CustomerTable,
			Columns: []string{paymentmethod.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentMethod{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentmethod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
