// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/occult/pagode/ent/paymentcustomer"
	"github.com/occult/pagode/ent/user"
)

// PaymentCustomer is the model entity for the PaymentCustomer schema.
type PaymentCustomer struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// External payment provider customer ID (e.g., Stripe customer ID)
	ProviderCustomerID string `json:"provider_customer_id,omitempty"`
	// Payment provider name
	Provider string `json:"provider,omitempty"`
	// Customer email from payment provider
	Email string `json:"email,omitempty"`
	// Customer name from payment provider
	Name string `json:"name,omitempty"`
	// Additional customer data from payment provider
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentCustomerQuery when eager-loading is set.
	Edges        PaymentCustomerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PaymentCustomerEdges holds the relations/edges for other nodes in the graph.
type PaymentCustomerEdges struct {
	// User associated with this payment customer
	User *User `json:"user,omitempty"`
	// Payment intents for this customer
	PaymentIntents []*PaymentIntent `json:"payment_intents,omitempty"`
	// Subscriptions for this customer
	Subscriptions []*Subscription `json:"subscriptions,omitempty"`
	// Payment methods for this customer
	PaymentMethods []*PaymentMethod `json:"payment_methods,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentCustomerEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PaymentIntentsOrErr returns the PaymentIntents value or an error if the edge
// was not loaded in eager-loading.
func (e PaymentCustomerEdges) PaymentIntentsOrErr() ([]*PaymentIntent, error) {
	if e.loadedTypes[1] {
		return e.PaymentIntents, nil
	}
	return nil, &NotLoadedError{edge: "payment_intents"}
}

// SubscriptionsOrErr returns the Subscriptions value or an error if the edge
// was not loaded in eager-loading.
func (e PaymentCustomerEdges) SubscriptionsOrErr() ([]*Subscription, error) {
	if e.loadedTypes[2] {
		return e.Subscriptions, nil
	}
	return nil, &NotLoadedError{edge: "subscriptions"}
}

// PaymentMethodsOrErr returns the PaymentMethods value or an error if the edge
// was not loaded in eager-loading.
func (e PaymentCustomerEdges) PaymentMethodsOrErr() ([]*PaymentMethod, error) {
	if e.loadedTypes[3] {
		return e.PaymentMethods, nil
	}
	return nil, &NotLoadedError{edge: "payment_methods"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentCustomer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentcustomer.FieldMetadata:
			values[i] = new([]byte)
		case paymentcustomer.FieldID:
			values[i] = new(sql.NullInt64)
		case paymentcustomer.FieldProviderCustomerID, paymentcustomer.FieldProvider, paymentcustomer.FieldEmail, paymentcustomer.FieldName:
			values[i] = new(sql.NullString)
		case paymentcustomer.FieldCreatedAt, paymentcustomer.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentCustomer fields.
func (_m *PaymentCustomer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentcustomer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case paymentcustomer.FieldProviderCustomerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_customer_id", values[i])
			} else if value.Valid {
				_m.ProviderCustomerID = value.String
			}
		case paymentcustomer.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case paymentcustomer.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case paymentcustomer.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case paymentcustomer.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case paymentcustomer.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paymentcustomer.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentCustomer.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentCustomer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PaymentCustomer entity.
func (_m *PaymentCustomer) QueryUser() *UserQuery {
	return NewPaymentCustomerClient(_m.config).QueryUser(_m)
}

// QueryPaymentIntents queries the "payment_intents" edge of the PaymentCustomer entity.
func (_m *PaymentCustomer) QueryPaymentIntents() *PaymentIntentQuery {
	return NewPaymentCustomerClient(_m.config).QueryPaymentIntents(_m)
}

// QuerySubscriptions queries the "subscriptions" edge of the PaymentCustomer entity.
func (_m *PaymentCustomer) QuerySubscriptions() *SubscriptionQuery {
	return NewPaymentCustomerClient(_m.config).QuerySubscriptions(_m)
}

// QueryPaymentMethods queries the "payment_methods" edge of the PaymentCustomer entity.
func (_m *PaymentCustomer) QueryPaymentMethods() *PaymentMethodQuery {
	return NewPaymentCustomerClient(_m.config).QueryPaymentMethods(_m)
}

// Update returns a builder for updating this PaymentCustomer.
// Note that you need to call PaymentCustomer.Unwrap() before calling this method if this PaymentCustomer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentCustomer) Update() *PaymentCustomerUpdateOne {
	return NewPaymentCustomerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentCustomer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentCustomer) Unwrap() *PaymentCustomer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentCustomer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentCustomer) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentCustomer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider_customer_id=")
	builder.WriteString(_m.ProviderCustomerID)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentCustomers is a parsable slice of PaymentCustomer.
type PaymentCustomers []*PaymentCustomer
