// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/occult/pagode/ent/paymentcustomer"
	"github.com/occult/pagode/ent/paymentintent"
	"github.com/occult/pagode/ent/predicate"
)

// PaymentIntentUpdate is the builder for updating PaymentIntent entities.
type PaymentIntentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentIntentMutation
}

// Where appends a list predicates to the PaymentIntentUpdate builder.
func (_u *PaymentIntentUpdate) Where(ps ...predicate.PaymentIntent) *PaymentIntentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderPaymentIntentID sets the "provider_payment_intent_id" field.
func (_u *PaymentIntentUpdate) SetProviderPaymentIntentID(v string) *PaymentIntentUpdate {
	_u.mutation.SetProviderPaymentIntentID(v)
	return _u
}

// SetNillableProviderPaymentIntentID sets the "provider_payment_intent_id" field if the given value is not nil.
func (_u *PaymentIntentUpdate) SetNillableProviderPaymentIntentID(v *string) *PaymentIntentUpdate {
	if v != nil {
		_u.SetProviderPaymentIntentID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentIntentUpdate) SetProvider(v string) *PaymentIntentUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentIntentUpdate) SetNillableProvider(v *string) *PaymentIntentUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentIntentUpdate) SetStatus(v paymentintent.Status) *PaymentIntentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentIntentUpdate) SetNillableStatus(v *paymentintent.Status) *PaymentIntentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentIntentUpdate) SetAmount(v int64) *PaymentIntentUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentIntentUpdate) SetNillableAmount(v *int64) *PaymentIntentUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentIntentUpdate) AddAmount(v int64) *PaymentIntentUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentIntentUpdate) SetCurrency(v string) *PaymentIntentUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentIntentUpdate) SetNillableCurrency(v *string) *PaymentIntentUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PaymentIntentUpdate) SetDescription(v string) *PaymentIntentUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PaymentIntentUpdate) SetNillableDescription(v *string) *PaymentIntentUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PaymentIntentUpdate) ClearDescription() *PaymentIntentUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetClientSecret sets the "client_secret" field.
func (_u *PaymentIntentUpdate) SetClientSecret(v string) *PaymentIntentUpdate {
	_u.mutation.SetClientSecret(v)
	return _u
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (_u *PaymentIntentUpdate) SetNillableClientSecret(v *string) *PaymentIntentUpdate {
	if v != nil {
		_u.SetClientSecret(*v)
	}
	return _u
}

// ClearClientSecret clears the value of the "client_secret" field.
func (_u *PaymentIntentUpdate) ClearClientSecret() *PaymentIntentUpdate {
	_u.mutation.ClearClientSecret()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PaymentIntentUpdate) SetMetadata(v map[string]interface{}) *PaymentIntentUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *PaymentIntentUpdate) ClearMetadata() *PaymentIntentUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentIntentUpdate) SetUpdatedAt(v time.Time) *PaymentIntentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCustomerID sets the "customer" edge to the PaymentCustomer entity by ID.
func (_u *PaymentIntentUpdate) SetCustomerID(id int) *PaymentIntentUpdate {
	_u.mutation.SetCustomerID(id)
	return _u
}

// SetCustomer sets the "customer" edge to the PaymentCustomer entity.
func (_u *PaymentIntentUpdate) SetCustomer(v *PaymentCustomer) *PaymentIntentUpdate {
	return _u.SetCustomerID(v.ID)
}

// Mutation returns the PaymentIntentMutation object of the builder.
func (_u *PaymentIntentUpdate) Mutation() *PaymentIntentMutation {
	return _u.mutation
}

// ClearCustomer clears the "customer" edge to the PaymentCustomer entity.
func (_u *PaymentIntentUpdate) ClearCustomer() *PaymentIntentUpdate {
	_u.mutation.ClearCustomer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentIntentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentIntentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentIntentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentIntentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentIntentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentintent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentIntentUpdate) check() error {
	if v, ok := _u.mutation.ProviderPaymentIntentID(); ok {
		if err := paymentintent.ProviderPaymentIntentIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_payment_intent_id", err: fmt.Errorf(`ent: validator failed for field "PaymentIntent.provider_payment_intent_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentintent.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentIntent.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentintent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentIntent.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := paymentintent.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "PaymentIntent.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentintent.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentIntent.currency": %w`, err)}
		}
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentIntent.customer"`)
	}
	return nil
}

func (_u *PaymentIntentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentintent.Table, paymentintent.Columns, sqlgraph.NewFieldSpec(paymentintent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderPaymentIntentID(); ok {
		_spec.SetField(paymentintent.FieldProviderPaymentIntentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentintent.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentintent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentintent.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentintent.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentintent.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(paymentintent.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(paymentintent.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ClientSecret(); ok {
		_spec.SetField(paymentintent.FieldClientSecret, field.TypeString, value)
	}
	if _u.mutation.ClientSecretCleared() {
		_spec.ClearField(paymentintent.FieldClientSecret, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(paymentintent.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(paymentintent.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentintent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentintent.CustomerTable,
			Columns: []string{paymentintent.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentintent.CustomerTable,
			Columns: []string{paymentintent.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentintent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentIntentUpdateOne is the builder for updating a single PaymentIntent entity.
type PaymentIntentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentIntentMutation
}

// SetProviderPaymentIntentID sets the "provider_payment_intent_id" field.
func (_u *PaymentIntentUpdateOne) SetProviderPaymentIntentID(v string) *PaymentIntentUpdateOne {
	_u.mutation.SetProviderPaymentIntentID(v)
	return _u
}

// SetNillableProviderPaymentIntentID sets the "provider_payment_intent_id" field if the given value is not nil.
func (_u *PaymentIntentUpdateOne) SetNillableProviderPaymentIntentID(v *string) *PaymentIntentUpdateOne {
	if v != nil {
		_u.SetProviderPaymentIntentID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentIntentUpdateOne) SetProvider(v string) *PaymentIntentUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentIntentUpdateOne) SetNillableProvider(v *string) *PaymentIntentUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentIntentUpdateOne) SetStatus(v paymentintent.Status) *PaymentIntentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentIntentUpdateOne) SetNillableStatus(v *paymentintent.Status) *PaymentIntentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentIntentUpdateOne) SetAmount(v int64) *PaymentIntentUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentIntentUpdateOne) SetNillableAmount(v *int64) *PaymentIntentUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentIntentUpdateOne) AddAmount(v int64) *PaymentIntentUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentIntentUpdateOne) SetCurrency(v string) *PaymentIntentUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentIntentUpdateOne) SetNillableCurrency(v *string) *PaymentIntentUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PaymentIntentUpdateOne) SetDescription(v string) *PaymentIntentUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PaymentIntentUpdateOne) SetNillableDescription(v *string) *PaymentIntentUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PaymentIntentUpdateOne) ClearDescription() *PaymentIntentUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetClientSecret sets the "client_secret" field.
func (_u *PaymentIntentUpdateOne) SetClientSecret(v string) *PaymentIntentUpdateOne {
	_u.mutation.SetClientSecret(v)
	return _u
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (_u *PaymentIntentUpdateOne) SetNillableClientSecret(v *string) *PaymentIntentUpdateOne {
	if v != nil {
		_u.SetClientSecret(*v)
	}
	return _u
}

// ClearClientSecret clears the value of the "client_secret" field.
func (_u *PaymentIntentUpdateOne) ClearClientSecret() *PaymentIntentUpdateOne {
	_u.mutation.ClearClientSecret()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PaymentIntentUpdateOne) SetMetadata(v map[string]interface{}) *PaymentIntentUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *PaymentIntentUpdateOne) ClearMetadata() *PaymentIntentUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentIntentUpdateOne) SetUpdatedAt(v time.Time) *PaymentIntentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCustomerID sets the "customer" edge to the PaymentCustomer entity by ID.
func (_u *PaymentIntentUpdateOne) SetCustomerID(id int) *PaymentIntentUpdateOne {
	_u.mutation.SetCustomerID(id)
	return _u
}

// SetCustomer sets the "customer" edge to the PaymentCustomer entity.
func (_u *PaymentIntentUpdateOne) SetCustomer(v *PaymentCustomer) *PaymentIntentUpdateOne {
	return _u.SetCustomerID(v.ID)
}

// Mutation returns the PaymentIntentMutation object of the builder.
func (_u *PaymentIntentUpdateOne) Mutation() *PaymentIntentMutation {
	return _u.mutation
}

// ClearCustomer clears the "customer" edge to the PaymentCustomer entity.
func (_u *PaymentIntentUpdateOne) ClearCustomer() *PaymentIntentUpdateOne {
	_u.mutation.ClearCustomer()
	return _u
}

// Where appends a list predicates to the PaymentIntentUpdate builder.
func (_u *PaymentIntentUpdateOne) Where(ps ...predicate.PaymentIntent) *PaymentIntentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentIntentUpdateOne) Select(field string, fields ...string) *PaymentIntentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentIntent entity.
func (_u *PaymentIntentUpdateOne) Save(ctx context.Context) (*PaymentIntent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentIntentUpdateOne) SaveX(ctx context.Context) *PaymentIntent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentIntentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentIntentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentIntentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentintent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentIntentUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderPaymentIntentID(); ok {
		if err := paymentintent.ProviderPaymentIntentIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_payment_intent_id", err: fmt.Errorf(`ent: validator failed for field "PaymentIntent.provider_payment_intent_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentintent.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentIntent.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentintent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentIntent.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := paymentintent.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "PaymentIntent.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentintent.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentIntent.currency": %w`, err)}
		}
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentIntent.customer"`)
	}
	return nil
}

func (_u *PaymentIntentUpdateOne) sqlSave(ctx context.Context) (_node *PaymentIntent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentintent.Table, paymentintent.Columns, sqlgraph.NewFieldSpec(paymentintent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentIntent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentintent.FieldID)
		for _, f := range fields {
			if !paymentintent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentintent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderPaymentIntentID(); ok {
		_spec.SetField(paymentintent.FieldProviderPaymentIntentID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentintent.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentintent.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentintent.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentintent.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentintent.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(paymentintent.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(paymentintent.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ClientSecret(); ok {
		_spec.SetField(paymentintent.FieldClientSecret, field.TypeString, value)
	}
	if _u.mutation.ClientSecretCleared() {
		_spec.ClearField(paymentintent.FieldClientSecret, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(paymentintent.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(paymentintent.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentintent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentintent.CustomerTable,
			Columns: []string{paymentintent.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentintent.CustomerTable,
			Columns: []string{paymentintent.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentIntent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentintent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
