// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/occult/pagode/ent/paymentcustomer"
	"github.com/occult/pagode/ent/predicate"
	"github.com/occult/pagode/ent/subscription"
)

// SubscriptionUpdate is the builder for updating Subscription entities.
type SubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionMutation
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdate) Where(ps ...predicate.Subscription) *SubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderSubscriptionID sets the "provider_subscription_id" field.
func (_u *SubscriptionUpdate) SetProviderSubscriptionID(v string) *SubscriptionUpdate {
	_u.mutation.SetProviderSubscriptionID(v)
	return _u
}

// SetNillableProviderSubscriptionID sets the "provider_subscription_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableProviderSubscriptionID(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetProviderSubscriptionID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *SubscriptionUpdate) SetProvider(v string) *SubscriptionUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableProvider(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdate) SetStatus(v subscription.Status) *SubscriptionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableStatus(v *subscription.Status) *SubscriptionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriceID sets the "price_id" field.
func (_u *SubscriptionUpdate) SetPriceID(v string) *SubscriptionUpdate {
	_u.mutation.SetPriceID(v)
	return _u
}

// SetNillablePriceID sets the "price_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillablePriceID(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetPriceID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *SubscriptionUpdate) SetAmount(v int64) *SubscriptionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableAmount(v *int64) *SubscriptionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *SubscriptionUpdate) AddAmount(v int64) *SubscriptionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *SubscriptionUpdate) SetCurrency(v string) *SubscriptionUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCurrency(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetInterval sets the "interval" field.
func (_u *SubscriptionUpdate) SetInterval(v subscription.Interval) *SubscriptionUpdate {
	_u.mutation.SetInterval(v)
	return _u
}

// SetNillableInterval sets the "interval" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableInterval(v *subscription.Interval) *SubscriptionUpdate {
	if v != nil {
		_u.SetInterval(*v)
	}
	return _u
}

// SetIntervalCount sets the "interval_count" field.
func (_u *SubscriptionUpdate) SetIntervalCount(v int) *SubscriptionUpdate {
	_u.mutation.ResetIntervalCount()
	_u.mutation.SetIntervalCount(v)
	return _u
}

// SetNillableIntervalCount sets the "interval_count" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableIntervalCount(v *int) *SubscriptionUpdate {
	if v != nil {
		_u.SetIntervalCount(*v)
	}
	return _u
}

// AddIntervalCount adds value to the "interval_count" field.
func (_u *SubscriptionUpdate) AddIntervalCount(v int) *SubscriptionUpdate {
	_u.mutation.AddIntervalCount(v)
	return _u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_u *SubscriptionUpdate) SetCurrentPeriodStart(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetCurrentPeriodStart(v)
	return _u
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCurrentPeriodStart(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetCurrentPeriodStart(*v)
	}
	return _u
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (_u *SubscriptionUpdate) ClearCurrentPeriodStart() *SubscriptionUpdate {
	_u.mutation.ClearCurrentPeriodStart()
	return _u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_u *SubscriptionUpdate) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetCurrentPeriodEnd(v)
	return _u
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCurrentPeriodEnd(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetCurrentPeriodEnd(*v)
	}
	return _u
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (_u *SubscriptionUpdate) ClearCurrentPeriodEnd() *SubscriptionUpdate {
	_u.mutation.ClearCurrentPeriodEnd()
	return _u
}

// SetTrialStart sets the "trial_start" field.
func (_u *SubscriptionUpdate) SetTrialStart(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetTrialStart(v)
	return _u
}

// SetNillableTrialStart sets the "trial_start" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableTrialStart(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetTrialStart(*v)
	}
	return _u
}

// ClearTrialStart clears the value of the "trial_start" field.
func (_u *SubscriptionUpdate) ClearTrialStart() *SubscriptionUpdate {
	_u.mutation.ClearTrialStart()
	return _u
}

// SetTrialEnd sets the "trial_end" field.
func (_u *SubscriptionUpdate) SetTrialEnd(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetTrialEnd(v)
	return _u
}

// SetNillableTrialEnd sets the "trial_end" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableTrialEnd(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetTrialEnd(*v)
	}
	return _u
}

// ClearTrialEnd clears the value of the "trial_end" field.
func (_u *SubscriptionUpdate) ClearTrialEnd() *SubscriptionUpdate {
	_u.mutation.ClearTrialEnd()
	return _u
}

// SetCanceledAt sets the "canceled_at" field.
func (_u *SubscriptionUpdate) SetCanceledAt(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetCanceledAt(v)
	return _u
}

// SetNillableCanceledAt sets the "canceled_at" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCanceledAt(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetCanceledAt(*v)
	}
	return _u
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (_u *SubscriptionUpdate) ClearCanceledAt() *SubscriptionUpdate {
	_u.mutation.ClearCanceledAt()
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SubscriptionUpdate) SetEndedAt(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableEndedAt(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SubscriptionUpdate) ClearEndedAt() *SubscriptionUpdate {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SubscriptionUpdate) SetMetadata(v map[string]interface{}) *SubscriptionUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SubscriptionUpdate) ClearMetadata() *SubscriptionUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdate) SetUpdatedAt(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCustomerID sets the "customer" edge to the PaymentCustomer entity by ID.
func (_u *SubscriptionUpdate) SetCustomerID(id int) *SubscriptionUpdate {
	_u.mutation.SetCustomerID(id)
	return _u
}

// SetCustomer sets the "customer" edge to the PaymentCustomer entity.
func (_u *SubscriptionUpdate) SetCustomer(v *PaymentCustomer) *SubscriptionUpdate {
	return _u.SetCustomerID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdate) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearCustomer clears the "customer" edge to the PaymentCustomer entity.
func (_u *SubscriptionUpdate) ClearCustomer() *SubscriptionUpdate {
	_u.mutation.ClearCustomer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdate) check() error {
	if v, ok := _u.mutation.ProviderSubscriptionID(); ok {
		if err := subscription.ProviderSubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_subscription_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.provider_subscription_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := subscription.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Subscription.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceID(); ok {
		if err := subscription.PriceIDValidator(v); err != nil {
			return &ValidationError{Name: "price_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.price_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := subscription.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Subscription.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := subscription.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Subscription.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Interval(); ok {
		if err := subscription.IntervalValidator(v); err != nil {
			return &ValidationError{Name: "interval", err: fmt.Errorf(`ent: validator failed for field "Subscription.interval": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IntervalCount(); ok {
		if err := subscription.IntervalCountValidator(v); err != nil {
			return &ValidationError{Name: "interval_count", err: fmt.Errorf(`ent: validator failed for field "Subscription.interval_count": %w`, err)}
		}
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subscription.customer"`)
	}
	return nil
}

func (_u *SubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderSubscriptionID(); ok {
		_spec.SetField(subscription.FieldProviderSubscriptionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(subscription.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PriceID(); ok {
		_spec.SetField(subscription.FieldPriceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(subscription.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(subscription.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(subscription.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Interval(); ok {
		_spec.SetField(subscription.FieldInterval, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IntervalCount(); ok {
		_spec.SetField(subscription.FieldIntervalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalCount(); ok {
		_spec.AddField(subscription.FieldIntervalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodStartCleared() {
		_spec.ClearField(subscription.FieldCurrentPeriodStart, field.TypeTime)
	}
	if value, ok := _u.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodEndCleared() {
		_spec.ClearField(subscription.FieldCurrentPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.TrialStart(); ok {
		_spec.SetField(subscription.FieldTrialStart, field.TypeTime, value)
	}
	if _u.mutation.TrialStartCleared() {
		_spec.ClearField(subscription.FieldTrialStart, field.TypeTime)
	}
	if value, ok := _u.mutation.TrialEnd(); ok {
		_spec.SetField(subscription.FieldTrialEnd, field.TypeTime, value)
	}
	if _u.mutation.TrialEndCleared() {
		_spec.ClearField(subscription.FieldTrialEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.CanceledAt(); ok {
		_spec.SetField(subscription.FieldCanceledAt, field.TypeTime, value)
	}
	if _u.mutation.CanceledAtCleared() {
		_spec.ClearField(subscription.FieldCanceledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(subscription.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(subscription.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(subscription.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(subscription.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.CustomerTable,
			Columns: []string{subscription.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.CustomerTable,
			Columns: []string{subscription.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionUpdateOne is the builder for updating a single Subscription entity.
type SubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionMutation
}

// SetProviderSubscriptionID sets the "provider_subscription_id" field.
func (_u *SubscriptionUpdateOne) SetProviderSubscriptionID(v string) *SubscriptionUpdateOne {
	_u.mutation.SetProviderSubscriptionID(v)
	return _u
}

// SetNillableProviderSubscriptionID sets the "provider_subscription_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableProviderSubscriptionID(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetProviderSubscriptionID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *SubscriptionUpdateOne) SetProvider(v string) *SubscriptionUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableProvider(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdateOne) SetStatus(v subscription.Status) *SubscriptionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableStatus(v *subscription.Status) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPriceID sets the "price_id" field.
func (_u *SubscriptionUpdateOne) SetPriceID(v string) *SubscriptionUpdateOne {
	_u.mutation.SetPriceID(v)
	return _u
}

// SetNillablePriceID sets the "price_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillablePriceID(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetPriceID(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *SubscriptionUpdateOne) SetAmount(v int64) *SubscriptionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableAmount(v *int64) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *SubscriptionUpdateOne) AddAmount(v int64) *SubscriptionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *SubscriptionUpdateOne) SetCurrency(v string) *SubscriptionUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCurrency(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetInterval sets the "interval" field.
func (_u *SubscriptionUpdateOne) SetInterval(v subscription.Interval) *SubscriptionUpdateOne {
	_u.mutation.SetInterval(v)
	return _u
}

// SetNillableInterval sets the "interval" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableInterval(v *subscription.Interval) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetInterval(*v)
	}
	return _u
}

// SetIntervalCount sets the "interval_count" field.
func (_u *SubscriptionUpdateOne) SetIntervalCount(v int) *SubscriptionUpdateOne {
	_u.mutation.ResetIntervalCount()
	_u.mutation.SetIntervalCount(v)
	return _u
}

// SetNillableIntervalCount sets the "interval_count" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableIntervalCount(v *int) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetIntervalCount(*v)
	}
	return _u
}

// AddIntervalCount adds value to the "interval_count" field.
func (_u *SubscriptionUpdateOne) AddIntervalCount(v int) *SubscriptionUpdateOne {
	_u.mutation.AddIntervalCount(v)
	return _u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_u *SubscriptionUpdateOne) SetCurrentPeriodStart(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetCurrentPeriodStart(v)
	return _u
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCurrentPeriodStart(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCurrentPeriodStart(*v)
	}
	return _u
}

// ClearCurrentPeriodStart clears the value of the "current_period_start" field.
func (_u *SubscriptionUpdateOne) ClearCurrentPeriodStart() *SubscriptionUpdateOne {
	_u.mutation.ClearCurrentPeriodStart()
	return _u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_u *SubscriptionUpdateOne) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetCurrentPeriodEnd(v)
	return _u
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCurrentPeriodEnd(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCurrentPeriodEnd(*v)
	}
	return _u
}

// ClearCurrentPeriodEnd clears the value of the "current_period_end" field.
func (_u *SubscriptionUpdateOne) ClearCurrentPeriodEnd() *SubscriptionUpdateOne {
	_u.mutation.ClearCurrentPeriodEnd()
	return _u
}

// SetTrialStart sets the "trial_start" field.
func (_u *SubscriptionUpdateOne) SetTrialStart(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetTrialStart(v)
	return _u
}

// SetNillableTrialStart sets the "trial_start" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableTrialStart(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetTrialStart(*v)
	}
	return _u
}

// ClearTrialStart clears the value of the "trial_start" field.
func (_u *SubscriptionUpdateOne) ClearTrialStart() *SubscriptionUpdateOne {
	_u.mutation.ClearTrialStart()
	return _u
}

// SetTrialEnd sets the "trial_end" field.
func (_u *SubscriptionUpdateOne) SetTrialEnd(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetTrialEnd(v)
	return _u
}

// SetNillableTrialEnd sets the "trial_end" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableTrialEnd(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetTrialEnd(*v)
	}
	return _u
}

// ClearTrialEnd clears the value of the "trial_end" field.
func (_u *SubscriptionUpdateOne) ClearTrialEnd() *SubscriptionUpdateOne {
	_u.mutation.ClearTrialEnd()
	return _u
}

// SetCanceledAt sets the "canceled_at" field.
func (_u *SubscriptionUpdateOne) SetCanceledAt(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetCanceledAt(v)
	return _u
}

// SetNillableCanceledAt sets the "canceled_at" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCanceledAt(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetCanceledAt(*v)
	}
	return _u
}

// ClearCanceledAt clears the value of the "canceled_at" field.
func (_u *SubscriptionUpdateOne) ClearCanceledAt() *SubscriptionUpdateOne {
	_u.mutation.ClearCanceledAt()
	return _u
}

// SetEndedAt sets the "ended_at" field.
func (_u *SubscriptionUpdateOne) SetEndedAt(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetEndedAt(v)
	return _u
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableEndedAt(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetEndedAt(*v)
	}
	return _u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (_u *SubscriptionUpdateOne) ClearEndedAt() *SubscriptionUpdateOne {
	_u.mutation.ClearEndedAt()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *SubscriptionUpdateOne) SetMetadata(v map[string]interface{}) *SubscriptionUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *SubscriptionUpdateOne) ClearMetadata() *SubscriptionUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCustomerID sets the "customer" edge to the PaymentCustomer entity by ID.
func (_u *SubscriptionUpdateOne) SetCustomerID(id int) *SubscriptionUpdateOne {
	_u.mutation.SetCustomerID(id)
	return _u
}

// SetCustomer sets the "customer" edge to the PaymentCustomer entity.
func (_u *SubscriptionUpdateOne) SetCustomer(v *PaymentCustomer) *SubscriptionUpdateOne {
	return _u.SetCustomerID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdateOne) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearCustomer clears the "customer" edge to the PaymentCustomer entity.
func (_u *SubscriptionUpdateOne) ClearCustomer() *SubscriptionUpdateOne {
	_u.mutation.ClearCustomer()
	return _u
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdateOne) Where(ps ...predicate.Subscription) *SubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionUpdateOne) Select(field string, fields ...string) *SubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Subscription entity.
func (_u *SubscriptionUpdateOne) Save(ctx context.Context) (*Subscription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) SaveX(ctx context.Context) *Subscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderSubscriptionID(); ok {
		if err := subscription.ProviderSubscriptionIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_subscription_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.provider_subscription_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := subscription.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Subscription.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceID(); ok {
		if err := subscription.PriceIDValidator(v); err != nil {
			return &ValidationError{Name: "price_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.price_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Amount(); ok {
		if err := subscription.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "Subscription.amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := subscription.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Subscription.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Interval(); ok {
		if err := subscription.IntervalValidator(v); err != nil {
			return &ValidationError{Name: "interval", err: fmt.Errorf(`ent: validator failed for field "Subscription.interval": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IntervalCount(); ok {
		if err := subscription.IntervalCountValidator(v); err != nil {
			return &ValidationError{Name: "interval_count", err: fmt.Errorf(`ent: validator failed for field "Subscription.interval_count": %w`, err)}
		}
	}
	if _u.mutation.CustomerCleared() && len(_u.mutation.CustomerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subscription.customer"`)
	}
	return nil
}

func (_u *SubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *Subscription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscription.FieldID)
		for _, f := range fields {
			if !subscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderSubscriptionID(); ok {
		_spec.SetField(subscription.FieldProviderSubscriptionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(subscription.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PriceID(); ok {
		_spec.SetField(subscription.FieldPriceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(subscription.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(subscription.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(subscription.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Interval(); ok {
		_spec.SetField(subscription.FieldInterval, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IntervalCount(); ok {
		_spec.SetField(subscription.FieldIntervalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalCount(); ok {
		_spec.AddField(subscription.FieldIntervalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodStartCleared() {
		_spec.ClearField(subscription.FieldCurrentPeriodStart, field.TypeTime)
	}
	if value, ok := _u.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if _u.mutation.CurrentPeriodEndCleared() {
		_spec.ClearField(subscription.FieldCurrentPeriodEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.TrialStart(); ok {
		_spec.SetField(subscription.FieldTrialStart, field.TypeTime, value)
	}
	if _u.mutation.TrialStartCleared() {
		_spec.ClearField(subscription.FieldTrialStart, field.TypeTime)
	}
	if value, ok := _u.mutation.TrialEnd(); ok {
		_spec.SetField(subscription.FieldTrialEnd, field.TypeTime, value)
	}
	if _u.mutation.TrialEndCleared() {
		_spec.ClearField(subscription.FieldTrialEnd, field.TypeTime)
	}
	if value, ok := _u.mutation.CanceledAt(); ok {
		_spec.SetField(subscription.FieldCanceledAt, field.TypeTime, value)
	}
	if _u.mutation.CanceledAtCleared() {
		_spec.ClearField(subscription.FieldCanceledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndedAt(); ok {
		_spec.SetField(subscription.FieldEndedAt, field.TypeTime, value)
	}
	if _u.mutation.EndedAtCleared() {
		_spec.ClearField(subscription.FieldEndedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(subscription.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(subscription.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.CustomerTable,
			Columns: []string{subscription.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.CustomerTable,
			Columns: []string{subscription.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentcustomer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Subscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
