// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/occult/pagode/ent/paymentcustomer"
	"github.com/occult/pagode/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"-"`
	// Verified holds the value of the "verified" field.
	Verified bool `json:"verified,omitempty"`
	// Admin holds the value of the "admin" field.
	Admin bool `json:"admin,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges                 UserEdges `json:"edges"`
	payment_customer_user *int
	selectValues          sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Owner holds the value of the owner edge.
	Owner []*PasswordToken `json:"owner,omitempty"`
	// PaymentCustomer holds the value of the payment_customer edge.
	PaymentCustomer *PaymentCustomer `json:"payment_customer,omitempty"`
	// OwnedChatRooms holds the value of the owned_chat_rooms edge.
	OwnedChatRooms []*ChatRoom `json:"owned_chat_rooms,omitempty"`
	// ChatMessages holds the value of the chat_messages edge.
	ChatMessages []*ChatMessage `json:"chat_messages,omitempty"`
	// ChatBans holds the value of the chat_bans edge.
	ChatBans []*ChatBan `json:"chat_bans,omitempty"`
	// ChatBansIssued holds the value of the chat_bans_issued edge.
	ChatBansIssued []*ChatBan `json:"chat_bans_issued,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) OwnerOrErr() ([]*PasswordToken, error) {
	if e.loadedTypes[0] {
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// PaymentCustomerOrErr returns the PaymentCustomer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) PaymentCustomerOrErr() (*PaymentCustomer, error) {
	if e.PaymentCustomer != nil {
		return e.PaymentCustomer, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: paymentcustomer.Label}
	}
	return nil, &NotLoadedError{edge: "payment_customer"}
}

// OwnedChatRoomsOrErr returns the OwnedChatRooms value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) OwnedChatRoomsOrErr() ([]*ChatRoom, error) {
	if e.loadedTypes[2] {
		return e.OwnedChatRooms, nil
	}
	return nil, &NotLoadedError{edge: "owned_chat_rooms"}
}

// ChatMessagesOrErr returns the ChatMessages value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ChatMessagesOrErr() ([]*ChatMessage, error) {
	if e.loadedTypes[3] {
		return e.ChatMessages, nil
	}
	return nil, &NotLoadedError{edge: "chat_messages"}
}

// ChatBansOrErr returns the ChatBans value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ChatBansOrErr() ([]*ChatBan, error) {
	if e.loadedTypes[4] {
		return e.ChatBans, nil
	}
	return nil, &NotLoadedError{edge: "chat_bans"}
}

// ChatBansIssuedOrErr returns the ChatBansIssued value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ChatBansIssuedOrErr() ([]*ChatBan, error) {
	if e.loadedTypes[5] {
		return e.ChatBansIssued, nil
	}
	return nil, &NotLoadedError{edge: "chat_bans_issued"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldVerified, user.FieldAdmin:
			values[i] = new(sql.NullBool)
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldName, user.FieldEmail, user.FieldPassword:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case user.ForeignKeys[0]: // payment_customer_user
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case user.FieldVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field verified", values[i])
			} else if value.Valid {
				_m.Verified = value.Bool
			}
		case user.FieldAdmin:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field admin", values[i])
			} else if value.Valid {
				_m.Admin = value.Bool
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field payment_customer_user", value)
			} else if value.Valid {
				_m.payment_customer_user = new(int)
				*_m.payment_customer_user = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the User entity.
func (_m *User) QueryOwner() *PasswordTokenQuery {
	return NewUserClient(_m.config).QueryOwner(_m)
}

// QueryPaymentCustomer queries the "payment_customer" edge of the User entity.
func (_m *User) QueryPaymentCustomer() *PaymentCustomerQuery {
	return NewUserClient(_m.config).QueryPaymentCustomer(_m)
}

// QueryOwnedChatRooms queries the "owned_chat_rooms" edge of the User entity.
func (_m *User) QueryOwnedChatRooms() *ChatRoomQuery {
	return NewUserClient(_m.config).QueryOwnedChatRooms(_m)
}

// QueryChatMessages queries the "chat_messages" edge of the User entity.
func (_m *User) QueryChatMessages() *ChatMessageQuery {
	return NewUserClient(_m.config).QueryChatMessages(_m)
}

// QueryChatBans queries the "chat_bans" edge of the User entity.
func (_m *User) QueryChatBans() *ChatBanQuery {
	return NewUserClient(_m.config).QueryChatBans(_m)
}

// QueryChatBansIssued queries the "chat_bans_issued" edge of the User entity.
func (_m *User) QueryChatBansIssued() *ChatBanQuery {
	return NewUserClient(_m.config).QueryChatBansIssued(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("verified=")
	builder.WriteString(fmt.Sprintf("%v", _m.Verified))
	builder.WriteString(", ")
	builder.WriteString("admin=")
	builder.WriteString(fmt.Sprintf("%v", _m.Admin))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
