// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ChatBan is the predicate function for chatban builders.
type ChatBan func(*sql.Selector)

// ChatMessage is the predicate function for chatmessage builders.
type ChatMessage func(*sql.Selector)

// ChatRoom is the predicate function for chatroom builders.
type ChatRoom func(*sql.Selector)

// PasswordToken is the predicate function for passwordtoken builders.
type PasswordToken func(*sql.Selector)

// PaymentCustomer is the predicate function for paymentcustomer builders.
type PaymentCustomer func(*sql.Selector)

// PaymentIntent is the predicate function for paymentintent builders.
type PaymentIntent func(*sql.Selector)

// PaymentMethod is the predicate function for paymentmethod builders.
type PaymentMethod func(*sql.Selector)

// Subscription is the predicate function for subscription builders.
type Subscription func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
